// ─────────────────────────────────────────────────────────────────────────────
// SubZeroMetrix — Vendor Categories
// 22 categories, 3–5 vendors each. affiliateStatus is factual — never fabricated.
// ─────────────────────────────────────────────────────────────────────────────

export type AffiliateStatus = 'none' | 'pending' | 'active'
export type SetupDifficulty = 'easy' | 'moderate' | 'advanced'
export type CostLevel = 'free' | 'low' | 'medium' | 'high' | 'enterprise'
export type ContractorStageTarget = 'startup' | 'early' | 'growth' | 'scale' | 'any'

export interface VendorEntry {
  id: string
  name: string
  categoryId: string
  websiteUrl: string
  affiliateStatus: AffiliateStatus
  tagline: string
  desc: string
  costLevel: CostLevel
  costNote: string
  setupDifficulty: SetupDifficulty
  bestFor: ContractorStageTarget[]
  tradeRelevance: string[]
  standoutFeature: string
  integrates: string[]
  freeOption: boolean
}

export interface VendorCategory {
  id: string
  label: string
  shortLabel: string
  icon: string
  description: string
  whyItMatters: string
  phaseRelevance: string[]
  vendors: VendorEntry[]
}

// ── Categories ─────────────────────────────────────────────────────────────────

export const VENDOR_CATEGORIES: VendorCategory[] = [

  {
    id: 'fsm',
    label: 'Field Service Management',
    shortLabel: 'FSM',
    icon: '📋',
    description: 'Platforms that manage scheduling, dispatch, job tracking, invoicing, and customer communication in one system.',
    whyItMatters: 'An FSM platform is the operational backbone of a service contractor. Without one, scheduling is in someone\'s head, invoicing is slow, and there is no visibility into what technicians are doing.',
    phaseRelevance: ['dispatch-scheduling-workflow', 'technician-performance'],
    vendors: [
      {
        id: 'servicetitan',
        name: 'ServiceTitan',
        categoryId: 'fsm',
        websiteUrl: 'https://www.servicetitan.com',
        affiliateStatus: 'none',
        tagline: 'Enterprise FSM for scaling contractors',
        desc: 'The most feature-rich FSM for residential and commercial service contractors. Covers scheduling, dispatch, flat-rate pricing, agreements, marketing, reporting, and payroll integration. Built for $1M+ revenue businesses.',
        costLevel: 'enterprise',
        costNote: 'Custom pricing, typically $300–$600+/month depending on technician count',
        setupDifficulty: 'advanced',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'plumbing', 'electrical'],
        standoutFeature: 'Best-in-class reporting, flat-rate price book, and marketing attribution tracking',
        integrates: ['quickbooks', 'Google Ads', 'Wisetack', 'Financeit'],
        freeOption: false,
      },
      {
        id: 'jobber',
        name: 'Jobber',
        categoryId: 'fsm',
        websiteUrl: 'https://getjobber.com',
        affiliateStatus: 'active',
        tagline: 'Scheduling, invoicing, and payments for field service',
        desc: 'Clean, practical FSM platform built for small-to-mid service businesses. Handles scheduling, dispatch, quoting, invoicing, payment collection, and customer communication. Faster to set up than ServiceTitan.',
        costLevel: 'medium',
        costNote: 'Starts at $49/month for Core, $149/month for Connect with all features',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Easy-to-use client hub, automated follow-ups, and online booking',
        integrates: ['quickbooks', 'stripe', 'google-calendar'],
        freeOption: false,
      },
      {
        id: 'housecall-pro',
        name: 'Housecall Pro',
        categoryId: 'fsm',
        websiteUrl: 'https://www.housecallpro.com',
        affiliateStatus: 'active',
        tagline: 'Run your home service business from your phone',
        desc: 'Mobile-first FSM with strong customer communication and review automation. Good for contractors who manage jobs primarily from a phone. Competitive with Jobber for ease of use.',
        costLevel: 'medium',
        costNote: 'Starts at $65/month for Basic, $169/month for Essentials with team features',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Automated review requests and strong mobile dispatch',
        integrates: ['quickbooks', 'stripe', 'google', 'mailchimp'],
        freeOption: false,
      },
      {
        id: 'fieldedge',
        name: 'FieldEdge',
        categoryId: 'fsm',
        websiteUrl: 'https://fieldedge.com',
        affiliateStatus: 'none',
        tagline: 'FSM built for HVAC and plumbing contractors',
        desc: 'Trade-specific FSM with a strong flat-rate price book, service agreements module, and QuickBooks integration. Popular with HVAC and plumbing companies as an alternative to ServiceTitan.',
        costLevel: 'high',
        costNote: 'Custom pricing, typically $100–$300/month',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'plumbing'],
        standoutFeature: 'Flat-rate price book and service agreement management',
        integrates: ['quickbooks', 'wisetack'],
        freeOption: false,
      },
      {
        id: 'service-fusion',
        name: 'Service Fusion',
        categoryId: 'fsm',
        websiteUrl: 'https://servicefusion.com',
        affiliateStatus: 'none',
        tagline: 'All-in-one FSM with flat-rate pricing and GPS',
        desc: 'FSM platform with built-in flat-rate pricing, GPS tracking, and QuickBooks sync. Good mid-market option for contractors who need more than Jobber but are not ready for ServiceTitan.',
        costLevel: 'medium',
        costNote: 'Starts at $149/month',
        setupDifficulty: 'moderate',
        bestFor: ['growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Built-in GPS tracking and flat-rate price catalog',
        integrates: ['quickbooks', 'google-maps'],
        freeOption: false,
      },
    ],
  },

  {
    id: 'crm',
    label: 'CRM & Sales Tracking',
    shortLabel: 'CRM',
    icon: '🤝',
    description: 'Customer relationship management tools for tracking leads, follow-ups, and sales pipeline.',
    whyItMatters: 'A CRM tracks every lead from first contact to closed job and beyond. Without one, follow-up is forgotten, leads fall through the cracks, and referral source data is lost.',
    phaseRelevance: ['sales-process-call-handling', 'followup-reviews-reputation'],
    vendors: [
      {
        id: 'hubspot-crm',
        name: 'HubSpot CRM',
        categoryId: 'crm',
        websiteUrl: 'https://www.hubspot.com/products/crm',
        affiliateStatus: 'none',
        tagline: 'Free CRM with email, pipeline, and contact tracking',
        desc: 'The most capable free CRM available. Tracks contacts, deals, emails, and activities. For contractors who need lead tracking beyond what their FSM provides. Good for commercial sales pipelines.',
        costLevel: 'free',
        costNote: 'Free forever for core CRM; paid plans start at $20/month for more automation',
        setupDifficulty: 'moderate',
        bestFor: ['early', 'growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Free tier includes email tracking, pipeline management, and deal reporting',
        integrates: ['gmail', 'outlook', 'zapier'],
        freeOption: true,
      },
      {
        id: 'pipedrive',
        name: 'Pipedrive',
        categoryId: 'crm',
        websiteUrl: 'https://www.pipedrive.com',
        affiliateStatus: 'none',
        tagline: 'Visual sales pipeline built for service businesses',
        desc: 'Sales CRM focused on pipeline visibility and activity tracking. Better for contractors with a commercial sales process or multiple estimators who need to manage quotes in stages.',
        costLevel: 'low',
        costNote: 'Starts at $14/user/month',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Visual pipeline view and automated activity reminders',
        integrates: ['google-workspace', 'mailchimp', 'zapier'],
        freeOption: false,
      },
      {
        id: 'callrail',
        name: 'CallRail',
        categoryId: 'crm',
        websiteUrl: 'https://www.callrail.com',
        affiliateStatus: 'none',
        tagline: 'Call tracking and lead intelligence for local businesses',
        desc: 'Tracks which marketing channels generate phone calls. Essential for contractors spending on Google, Angi, Thumbtack, or direct mail who want to know which channels actually convert to booked jobs.',
        costLevel: 'low',
        costNote: 'Starts at $45/month for call tracking with recording',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Dynamic number insertion attributes calls to specific campaigns',
        integrates: ['google-ads', 'google-analytics', 'hubspot'],
        freeOption: false,
      },
    ],
  },

  {
    id: 'estimating',
    label: 'Estimating Software',
    shortLabel: 'Estimating',
    icon: '📐',
    description: 'Tools for creating professional estimates, proposals, and flat-rate price books.',
    whyItMatters: 'Professional, fast estimating increases close rates and prevents margin erosion from under-pricing. A price book removes the guesswork from quoting.',
    phaseRelevance: ['pricing-profit-margin'],
    vendors: [
      {
        id: 'servicetitan-pricing',
        name: 'ServiceTitan (price book)',
        categoryId: 'estimating',
        websiteUrl: 'https://www.servicetitan.com',
        affiliateStatus: 'none',
        tagline: 'Industry-standard flat-rate price book for service trades',
        desc: 'ServiceTitan\'s flat-rate price book is the most complete pricing tool for HVAC, plumbing, and electrical contractors. Requires a ServiceTitan subscription.',
        costLevel: 'enterprise',
        costNote: 'Included in ServiceTitan subscription',
        setupDifficulty: 'advanced',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'plumbing', 'electrical'],
        standoutFeature: 'Pre-built trade-specific price books with labor and material pricing',
        integrates: ['servicetitan'],
        freeOption: false,
      },
      {
        id: 'jobber-quoting',
        name: 'Jobber (quoting)',
        categoryId: 'estimating',
        websiteUrl: 'https://getjobber.com',
        affiliateStatus: 'active',
        tagline: 'Fast, professional quotes from your phone or laptop',
        desc: 'Jobber\'s quoting module lets you build and send professional estimates, track approval, and convert to jobs in one click. Good for line-item or flat-rate quoting for smaller operations.',
        costLevel: 'medium',
        costNote: 'Included in Jobber Connect plan at $149/month',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Online quote approval and instant job conversion',
        integrates: ['quickbooks', 'stripe'],
        freeOption: false,
      },
      {
        id: 'buildxact',
        name: 'Buildxact',
        categoryId: 'estimating',
        websiteUrl: 'https://www.buildxact.com',
        affiliateStatus: 'none',
        tagline: 'Takeoff and estimating for builders and remodelers',
        desc: 'Takeoff and cost estimating software for residential builders, remodelers, and construction contractors. Includes material quantity takeoff from plans, supplier price books, and proposal generation.',
        costLevel: 'medium',
        costNote: 'Starts at $149/month',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['construction', 'roofing'],
        standoutFeature: 'Digital plan takeoff with supplier cost integration',
        integrates: ['xero', 'quickbooks'],
        freeOption: false,
      },
      {
        id: 'simprogroup',
        name: 'Simpro',
        categoryId: 'estimating',
        websiteUrl: 'https://www.simprogroup.com',
        affiliateStatus: 'none',
        tagline: 'End-to-end quoting and job management for trade contractors',
        desc: 'Comprehensive quote-to-cash platform for electrical, plumbing, HVAC, and mechanical contractors. Stronger job costing and multi-stage project management than typical FSM platforms.',
        costLevel: 'high',
        costNote: 'Custom pricing',
        setupDifficulty: 'advanced',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['electrical', 'plumbing', 'hvac', 'construction'],
        standoutFeature: 'Strong job costing and project stage billing for complex multi-phase jobs',
        integrates: ['quickbooks', 'xero', 'sage'],
        freeOption: false,
      },
    ],
  },

  {
    id: 'payments',
    label: 'Payments & Invoicing',
    shortLabel: 'Payments',
    icon: '💳',
    description: 'Tools for collecting payments in the field and managing invoicing.',
    whyItMatters: 'Fast payment collection improves cash flow and reduces bad debt. Customers who can pay by card or ACH on-site pay faster and leave better reviews than those chased down for checks.',
    phaseRelevance: ['banking-finance'],
    vendors: [
      {
        id: 'stripe',
        name: 'Stripe',
        categoryId: 'payments',
        websiteUrl: 'https://stripe.com',
        affiliateStatus: 'none',
        tagline: 'Developer-friendly payment infrastructure',
        desc: 'The most widely integrated payment processor. Powers many FSM platforms\' built-in payment tools. Used directly by contractors who need custom payment flows or subscription billing for maintenance agreements.',
        costLevel: 'low',
        costNote: '2.9% + $0.30 per card transaction; no monthly fee',
        setupDifficulty: 'moderate',
        bestFor: ['any'],
        tradeRelevance: ['all'],
        standoutFeature: 'Best-in-class developer API and recurring billing for maintenance agreements',
        integrates: ['jobber', 'quickbooks', 'housecall-pro'],
        freeOption: false,
      },
      {
        id: 'square',
        name: 'Square',
        categoryId: 'payments',
        websiteUrl: 'https://squareup.com',
        affiliateStatus: 'none',
        tagline: 'Free card reader, simple flat-rate processing',
        desc: 'Easiest way to start accepting card payments in the field. Free card reader, 2.6% + $0.10 per swipe, instant deposits available. Not as integrated as Jobber/HCP payments, but works standalone.',
        costLevel: 'low',
        costNote: '2.6% + $0.10 per tap/dip/swipe; no monthly fee',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early'],
        tradeRelevance: ['all'],
        standoutFeature: 'Instant free card reader and zero monthly fee to start',
        integrates: ['quickbooks', 'xero'],
        freeOption: true,
      },
      {
        id: 'jobber-payments',
        name: 'Jobber Payments',
        categoryId: 'payments',
        websiteUrl: 'https://getjobber.com/features/payments',
        affiliateStatus: 'active',
        tagline: 'Payments built into your FSM workflow',
        desc: 'Accept card and ACH directly in Jobber. Invoice auto-closes when paid. Customer card on file for recurring billing. Eliminates the friction of using a separate payment tool when you are already in Jobber.',
        costLevel: 'low',
        costNote: '2.9% + $0.30 per transaction; no setup fee',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Payments built directly into Jobber job close — no separate tool',
        integrates: ['jobber'],
        freeOption: false,
      },
    ],
  },

  {
    id: 'financing',
    label: 'Homeowner Financing',
    shortLabel: 'Financing',
    icon: '🏦',
    description: 'Consumer financing solutions that let homeowners pay monthly for larger jobs.',
    whyItMatters: 'Financing is the single most effective tool for closing large-ticket residential jobs. Customers who cannot afford $5,000 upfront can afford $89/month. Financing-offered jobs close at significantly higher rates.',
    phaseRelevance: ['pricing-profit-margin'],
    vendors: [
      {
        id: 'wisetack',
        name: 'Wisetack',
        categoryId: 'financing',
        websiteUrl: 'https://www.wisetack.com',
        affiliateStatus: 'pending',
        tagline: 'Consumer financing built for home services',
        desc: 'Point-of-sale consumer financing purpose-built for home service contractors. Integrates directly with ServiceTitan, Jobber, and Housecall Pro. Customers apply in 60 seconds on their phone.',
        costLevel: 'low',
        costNote: 'No cost to contractor; merchant fee deducted from loan amount (typically 3–9%)',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth', 'scale'],
        tradeRelevance: ['hvac', 'plumbing', 'electrical', 'roofing', 'construction'],
        standoutFeature: 'Direct FSM integration — financing offered in the same flow as the estimate',
        integrates: ['servicetitan', 'jobber', 'housecall-pro'],
        freeOption: false,
      },
      {
        id: 'greensky',
        name: 'GreenSky',
        categoryId: 'financing',
        websiteUrl: 'https://www.greensky.com',
        affiliateStatus: 'none',
        tagline: 'Home improvement financing at point of sale',
        desc: 'Established consumer lending platform widely used by HVAC, roofing, and remodeling contractors. Promotional financing options (deferred interest, same-as-cash) effective on large HVAC and roofing tickets.',
        costLevel: 'low',
        costNote: 'Merchant fee varies by promo terms; typically 3–8%',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'roofing', 'construction'],
        standoutFeature: 'Same-as-cash promotional terms that close hesitant replacement buyers',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'hearth',
        name: 'Hearth',
        categoryId: 'financing',
        websiteUrl: 'https://www.gethearth.com',
        affiliateStatus: 'none',
        tagline: 'Fast financing approval for home service contractors',
        desc: 'Online financing platform for home service companies. Customers check their rate in 60 seconds without a hard credit pull. Used by roofing, HVAC, plumbing, and electrical contractors.',
        costLevel: 'low',
        costNote: 'SaaS fee starting at $65/month; no merchant fee',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'No merchant fee model — contractor pays flat SaaS cost instead',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'service-finance',
        name: 'Service Finance Company',
        categoryId: 'financing',
        websiteUrl: 'https://www.servicefinanceco.com',
        affiliateStatus: 'none',
        tagline: 'Long-term financing for HVAC and home improvements',
        desc: 'Specialty home improvement lender with competitive long-term rates and high loan amounts. Common in HVAC and large home services. Longer-term loans at lower APR than typical point-of-sale options.',
        costLevel: 'low',
        costNote: 'Merchant discount rate varies by program; typically 4–9%',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'electrical', 'construction'],
        standoutFeature: 'Higher loan amounts and longer terms than typical POS financing options',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'goodleap',
        name: 'GoodLeap',
        categoryId: 'financing',
        websiteUrl: 'https://www.goodleap.com',
        affiliateStatus: 'none',
        tagline: 'Homeowner financing for home improvement and energy upgrades',
        desc: 'Home improvement financing platform strong in solar, roofing, HVAC, and energy efficiency upgrades. Fast approvals and high loan amounts make it competitive for larger replacement and improvement projects.',
        costLevel: 'low',
        costNote: 'Merchant discount rate varies; typically 3–8% depending on program',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'roofing', 'electrical', 'construction'],
        standoutFeature: 'Strong approval rates on large home improvement and energy upgrade projects',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'synchrony-home',
        name: 'Synchrony Home',
        categoryId: 'financing',
        websiteUrl: 'https://www.synchrony.com/business/home',
        affiliateStatus: 'none',
        tagline: 'Point-of-sale financing for home services and improvements',
        desc: 'Established consumer financing program used by HVAC, plumbing, and remodeling contractors. Synchrony Home offers deferred interest and low-payment plans that customers recognize and trust.',
        costLevel: 'low',
        costNote: 'Merchant fees vary by program; contact for rates',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'plumbing', 'construction'],
        standoutFeature: 'Widely recognized consumer brand that reduces customer financing hesitation',
        integrates: [],
        freeOption: false,
      },
    ],
  },

  {
    id: 'banking',
    label: 'Business Banking',
    shortLabel: 'Banking',
    icon: '🏛️',
    description: 'Business checking and banking solutions for contractors.',
    whyItMatters: 'A business bank account separate from personal finances is foundational. The right bank also provides lending relationships, credit lines, and credit card programs as the business grows.',
    phaseRelevance: ['foundation-setup', 'banking-finance'],
    vendors: [
      {
        id: 'relay',
        name: 'Relay',
        categoryId: 'banking',
        websiteUrl: 'https://relayfi.com',
        affiliateStatus: 'active',
        tagline: 'Online banking built for small business owners',
        desc: 'Online business bank with no monthly fees, multiple account support, free debit cards, and accountant access. Ideal for contractors who want free banking with clean software. Not a traditional bank but FDIC insured through partner banks.',
        costLevel: 'free',
        costNote: 'No monthly fee; fee-based premium tier available',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Multiple sub-accounts for tax reserve, operating, and payroll separation',
        integrates: ['quickbooks', 'xero', 'gusto'],
        freeOption: true,
      },
      {
        id: 'mercury',
        name: 'Mercury',
        categoryId: 'banking',
        websiteUrl: 'https://mercury.com',
        affiliateStatus: 'none',
        tagline: 'Business banking built for startups and growing companies',
        desc: 'Online business bank with no fees, virtual cards, strong API access, and team permissions. Excellent for contractors who want modern banking software. FDIC insured through Evolve Bank & Trust.',
        costLevel: 'free',
        costNote: 'No monthly fee; Treasury product earns interest',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Clean UI, virtual cards for vendor spending, and team permissions',
        integrates: ['quickbooks', 'xero', 'stripe'],
        freeOption: true,
      },
      {
        id: 'chase-business',
        name: 'Chase Business Checking',
        categoryId: 'banking',
        websiteUrl: 'https://www.chase.com/business',
        affiliateStatus: 'none',
        tagline: 'Traditional bank with SBA lending and credit access',
        desc: 'Largest US bank by assets. Preferred by contractors who want a traditional banking relationship for future SBA loans, lines of credit, or equipment financing. Monthly fee waivable with minimum balance.',
        costLevel: 'low',
        costNote: '$15/month fee, waivable with $2,000+ daily balance',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Strongest SBA and business credit lending relationship in the industry',
        integrates: ['quickbooks'],
        freeOption: false,
      },
      {
        id: 'bluevine',
        name: 'Bluevine Business Checking',
        categoryId: 'banking',
        websiteUrl: 'https://www.bluevine.com',
        affiliateStatus: 'none',
        tagline: 'High-yield business checking with built-in credit line',
        desc: 'Online business banking with interest-bearing checking (up to 2% on balances) and easy access to revolving lines of credit. Good for contractors who want banking and credit access in one place.',
        costLevel: 'free',
        costNote: 'No monthly fee; credit line products have draw fees',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Built-in business line of credit access alongside checking account',
        integrates: ['quickbooks'],
        freeOption: true,
      },
    ],
  },

  {
    id: 'accounting',
    label: 'Accounting & Bookkeeping',
    shortLabel: 'Accounting',
    icon: '📊',
    description: 'Accounting software and bookkeeping tools for tracking income, expenses, and job costs.',
    whyItMatters: 'Accurate bookkeeping is the foundation of financial control. Without it, you cannot know your true margins, plan for taxes, or present clean financials to a lender.',
    phaseRelevance: ['banking-finance'],
    vendors: [
      {
        id: 'quickbooks',
        name: 'QuickBooks Online',
        categoryId: 'accounting',
        websiteUrl: 'https://quickbooks.intuit.com',
        affiliateStatus: 'active',
        tagline: 'The industry standard for small business accounting',
        desc: 'The most widely used accounting software for small businesses. Connects with nearly every FSM, bank, and payroll provider. Required by most CPAs and lenders when reviewing contractor financials.',
        costLevel: 'medium',
        costNote: 'Starts at $30/month for Simple Start; $60/month for Plus with job costing',
        setupDifficulty: 'moderate',
        bestFor: ['any'],
        tradeRelevance: ['all'],
        standoutFeature: 'Universal FSM integration and industry-standard format for CPA and lender review',
        integrates: ['jobber', 'housecall-pro', 'servicetitan', 'gusto', 'relay'],
        freeOption: false,
      },
      {
        id: 'wave',
        name: 'Wave Accounting',
        categoryId: 'accounting',
        websiteUrl: 'https://www.waveapps.com',
        affiliateStatus: 'active',
        tagline: 'Free accounting, invoicing, and expense tracking',
        desc: 'Completely free accounting, invoicing, and expense tracking for small businesses. Lacks job costing depth but excellent for sole proprietors and early-stage contractors who need basic income/expense tracking without cost.',
        costLevel: 'free',
        costNote: 'Accounting is free; payroll and payment processing are paid add-ons',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early'],
        tradeRelevance: ['all'],
        standoutFeature: 'Fully free accounting and invoicing with no transaction limits',
        integrates: ['stripe', 'google-sheets'],
        freeOption: true,
      },
      {
        id: 'knowify',
        name: 'Knowify',
        categoryId: 'accounting',
        websiteUrl: 'https://www.knowify.com',
        affiliateStatus: 'none',
        tagline: 'Job costing and project management for trade contractors',
        desc: 'Contractor-specific software for job costing, budgeting, and project tracking. Syncs with QuickBooks. Purpose-built for contractors who need per-job profit visibility that QuickBooks alone does not provide.',
        costLevel: 'medium',
        costNote: 'Starts at $83/month',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['construction', 'hvac', 'electrical', 'plumbing'],
        standoutFeature: 'Real-time job cost tracking vs. estimate with QuickBooks sync',
        integrates: ['quickbooks'],
        freeOption: false,
      },
      {
        id: 'xero',
        name: 'Xero',
        categoryId: 'accounting',
        websiteUrl: 'https://www.xero.com',
        affiliateStatus: 'none',
        tagline: 'Cloud accounting software for small businesses',
        desc: 'Cloud-based accounting platform popular with contractors who prefer a clean interface and strong bank reconciliation. Integrates with many trade apps and handles job costing through add-ons.',
        costLevel: 'medium',
        costNote: 'Starts at $15/month for Early, $42/month for Growing',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Real-time bank feeds and clean mobile reconciliation',
        integrates: ['servicetitan', 'jobber', 'stripe'],
        freeOption: false,
      },
      {
        id: 'freshbooks',
        name: 'FreshBooks',
        categoryId: 'accounting',
        websiteUrl: 'https://www.freshbooks.com',
        affiliateStatus: 'none',
        tagline: 'Simple invoicing and accounting for small contractors',
        desc: 'User-friendly accounting and invoicing platform suited for solo operators and small crews. Handles time tracking, expenses, and basic job-level reporting. Easier to learn than QuickBooks for non-accountants.',
        costLevel: 'low',
        costNote: 'Starts at $19/month for Lite (5 clients); $33/month for Plus',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early'],
        tradeRelevance: ['all'],
        standoutFeature: 'Fastest invoicing workflow for solo operators and small crews',
        integrates: ['stripe', 'zapier'],
        freeOption: false,
      },
    ],
  },

  {
    id: 'payroll',
    label: 'Payroll',
    shortLabel: 'Payroll',
    icon: '👷',
    description: 'Payroll processing, tax filing, and HR compliance tools.',
    whyItMatters: 'Payroll mistakes are expensive — back taxes, penalties, and misclassification liability. Automated payroll ensures compliance and frees the owner from manual calculation.',
    phaseRelevance: ['scaling-hiring-leadership'],
    vendors: [
      {
        id: 'gusto',
        name: 'Gusto',
        categoryId: 'payroll',
        websiteUrl: 'https://gusto.com',
        affiliateStatus: 'none',
        tagline: 'Payroll, benefits, and HR for growing businesses',
        desc: 'The most popular online payroll platform for small businesses. Handles payroll taxes automatically, offers employee benefits administration, and includes basic HR features. Integrates with QuickBooks and most accounting software.',
        costLevel: 'medium',
        costNote: 'Starts at $40/month + $6/employee for Simple tier',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Automatic payroll tax filing at federal, state, and local level',
        integrates: ['quickbooks', 'xero', 'relay'],
        freeOption: false,
      },
      {
        id: 'qb-payroll',
        name: 'QuickBooks Payroll',
        categoryId: 'payroll',
        websiteUrl: 'https://quickbooks.intuit.com/payroll',
        affiliateStatus: 'active',
        tagline: 'Payroll built into your QuickBooks accounting',
        desc: 'Payroll that lives inside QuickBooks. Preferred by contractors already on QuickBooks who want minimal integration work. Automatic tax payments, direct deposit, and workers\' comp pay-as-you-go.',
        costLevel: 'medium',
        costNote: 'Starts at $45/month + $6/employee for Core',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Seamless payroll-to-accounting sync when already on QuickBooks',
        integrates: ['quickbooks'],
        freeOption: false,
      },
      {
        id: 'adp',
        name: 'ADP Run',
        categoryId: 'payroll',
        websiteUrl: 'https://www.adp.com/solutions/small-business/payroll.aspx',
        affiliateStatus: 'none',
        tagline: 'Full-service payroll and HR for small businesses',
        desc: 'Industry-leading payroll provider with strong HR, compliance, and workers\' comp integration. Better than Gusto for contractors with more complex payroll needs (certified payroll, prevailing wage, union reporting).',
        costLevel: 'high',
        costNote: 'Custom pricing; typically $60–$150/month depending on employee count',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Certified payroll reporting for prevailing wage and government contracts',
        integrates: ['quickbooks'],
        freeOption: false,
      },
      {
        id: 'paychex',
        name: 'Paychex Flex',
        categoryId: 'payroll',
        websiteUrl: 'https://www.paychex.com',
        affiliateStatus: 'none',
        tagline: 'Full-service payroll and HR for growing businesses',
        desc: 'Large-scale payroll and HR platform with strong compliance support. Good fit for contractors scaling past 10 employees who need certified payroll, multi-state filing, and dedicated HR resources.',
        costLevel: 'high',
        costNote: 'Custom pricing; typically $60–$160/month depending on employee count',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Dedicated payroll specialist support and strong multi-state compliance',
        integrates: ['quickbooks'],
        freeOption: false,
      },
      {
        id: 'clockshark',
        name: 'ClockShark',
        categoryId: 'payroll',
        websiteUrl: 'https://www.clockshark.com',
        affiliateStatus: 'none',
        tagline: 'Field crew time tracking for contractors',
        desc: 'GPS-enabled time tracking built specifically for field service and construction crews. Captures clock-in location, job assignment, and labor hours for payroll and job costing. Built for crews who do not sit at a desk.',
        costLevel: 'low',
        costNote: 'Starts at $16/month base + $8/user/month',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'GPS-verified clock-in tied to specific job sites and job codes',
        integrates: ['quickbooks', 'gusto', 'adp'],
        freeOption: false,
      },
    ],
  },

  {
    id: 'insurance',
    label: 'Business Insurance',
    shortLabel: 'Insurance',
    icon: '🛡️',
    description: 'General liability, commercial auto, workers compensation, and specialty coverage for contractors.',
    whyItMatters: 'Insurance is not optional for contractors. One job gone wrong without coverage ends the business. Licensed contractors on commercial work are required to maintain active certificates.',
    phaseRelevance: ['foundation-setup'],
    vendors: [
      {
        id: 'next-insurance',
        name: 'NEXT Insurance',
        categoryId: 'insurance',
        websiteUrl: 'https://www.nextinsurance.com',
        affiliateStatus: 'active',
        tagline: 'Fast, affordable contractor insurance online',
        desc: 'Online-first insurance designed for small contractors and self-employed tradespeople. Fast quote and bind (often same day), instant certificates, and competitive pricing for GL and tools/equipment coverage.',
        costLevel: 'low',
        costNote: 'GL starts around $500–$1,500/year for most trades depending on revenue and trade',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early'],
        tradeRelevance: ['all'],
        standoutFeature: 'Instant certificate issuance from your phone — critical for commercial work',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'simply-business',
        name: 'Simply Business',
        categoryId: 'insurance',
        websiteUrl: 'https://www.simplybusiness.com',
        affiliateStatus: 'active',
        tagline: 'Compare multiple insurance quotes for contractors',
        desc: 'Insurance marketplace that compares quotes from multiple carriers. Good for finding competitive rates across GL, professional liability, and commercial auto. Specializes in small business and contractor coverage.',
        costLevel: 'low',
        costNote: 'Quote comparison service; pricing varies by coverage type and carrier',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early'],
        tradeRelevance: ['all'],
        standoutFeature: 'Multi-carrier comparison for contractor GL and tools coverage in one place',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'biberk',
        name: 'biBERK (Berkshire Hathaway)',
        categoryId: 'insurance',
        websiteUrl: 'https://www.biberk.com',
        affiliateStatus: 'none',
        tagline: 'Berkshire Hathaway-backed contractor insurance',
        desc: 'Direct-from-carrier insurance (backed by Berkshire Hathaway) for small contractors. GL, workers comp, commercial auto, umbrella. Good mid-market option with strong carrier backing and competitive rates.',
        costLevel: 'low',
        costNote: 'GL starts around $500–$2,000/year; workers comp varies by payroll and classification',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Direct carrier relationship with strong financial backing — no broker markup',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'hiscox',
        name: 'Hiscox',
        categoryId: 'insurance',
        websiteUrl: 'https://www.hiscox.com/small-business-insurance',
        affiliateStatus: 'none',
        tagline: 'Specialist insurance for contractors and home services',
        desc: 'Specialty insurer with strong contractor and professional liability coverage. Often preferred for contractors doing commercial work where carrier reputation matters for certificate acceptance.',
        costLevel: 'medium',
        costNote: 'GL starts around $500–$3,000/year depending on trade and revenue',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Specialist contractor underwriting — accepts more complex trade classifications',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'the-hartford',
        name: 'The Hartford',
        categoryId: 'insurance',
        websiteUrl: 'https://www.thehartford.com/small-business-insurance/contractors',
        affiliateStatus: 'none',
        tagline: 'Business insurance for contractors from a trusted national carrier',
        desc: 'One of the most recognized small business insurance carriers with strong general liability, business owner policy, and workers compensation programs for contractors. Accepted widely on commercial bids and government jobs.',
        costLevel: 'medium',
        costNote: 'GL starts around $500–$4,000/year depending on trade, revenue, and payroll',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Nationally recognized carrier — certificates accepted on commercial and government bids',
        integrates: [],
        freeOption: false,
      },
    ],
  },

  {
    id: 'credit-cards',
    label: 'Business Credit Cards',
    shortLabel: 'Credit Cards',
    icon: '💳',
    description: 'Business credit cards for purchasing materials, building business credit, and earning rewards.',
    whyItMatters: 'A business credit card builds your business credit score, earns rewards on material purchases, and creates an expense record separate from your personal accounts. Never use a personal card for business expenses.',
    phaseRelevance: ['foundation-setup', 'banking-finance'],
    vendors: [
      {
        id: 'chase-ink',
        name: 'Chase Ink Business Cash',
        categoryId: 'credit-cards',
        websiteUrl: 'https://creditcards.chase.com/business-credit-cards/ink',
        affiliateStatus: 'none',
        tagline: '5% cash back on office supplies and internet/phone',
        desc: 'No annual fee business credit card with 5% back at office supply stores and on internet/cable/phone, 2% back on gas and dining. Strong starting card for contractors building business credit.',
        costLevel: 'free',
        costNote: 'No annual fee',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'No annual fee and strong rewards on operational categories for contractors',
        integrates: ['quickbooks'],
        freeOption: true,
      },
      {
        id: 'capital-one-spark',
        name: 'Capital One Spark Cash Plus',
        categoryId: 'credit-cards',
        websiteUrl: 'https://www.capitalone.com/small-business/credit-cards/spark-cash-plus',
        affiliateStatus: 'none',
        tagline: 'Unlimited 2% cash back on all business purchases',
        desc: 'Simple, flat 2% cash back on all purchases — no category management. Best for contractors who want maximum simplicity and earn most of their spend on materials and fuel. Charge card with no preset limit.',
        costLevel: 'low',
        costNote: '$150 annual fee',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Flat 2% on everything — no categories to track, no caps',
        integrates: ['quickbooks'],
        freeOption: false,
      },
      {
        id: 'ramp',
        name: 'Ramp',
        categoryId: 'credit-cards',
        websiteUrl: 'https://ramp.com',
        affiliateStatus: 'none',
        tagline: 'Corporate cards with expense automation',
        desc: 'Corporate card and expense management platform. Issues individual cards to techs or field managers with spend controls. Excellent for larger operations where you need to manage multiple employee spending.',
        costLevel: 'free',
        costNote: 'No annual fee; card program is free',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Per-employee spend controls and automated expense categorization',
        integrates: ['quickbooks', 'xero', 'gusto'],
        freeOption: true,
      },
    ],
  },

  {
    id: 'lending',
    label: 'Business Lending & Credit',
    shortLabel: 'Lending',
    icon: '📈',
    description: 'Business loans, lines of credit, and equipment financing for contractors.',
    whyItMatters: 'Access to capital at the right time enables equipment purchases, hiring, and seasonal cash flow management. The right lending relationship also builds business credit for future growth.',
    phaseRelevance: ['banking-finance', 'scaling-hiring-leadership'],
    vendors: [
      {
        id: 'bluevine-credit',
        name: 'Bluevine Line of Credit',
        categoryId: 'lending',
        websiteUrl: 'https://www.bluevine.com/business-line-of-credit',
        affiliateStatus: 'none',
        tagline: 'Flexible revolving credit line for small businesses',
        desc: 'Revolving business line of credit up to $250,000. No draw fee if repaid within term. Good option for contractors managing seasonal cash flow gaps or funding material purchases before customer payment arrives.',
        costLevel: 'low',
        costNote: 'Weekly repayment; rates vary based on creditworthiness',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Fast approval (often same-day) without traditional bank requirements',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'fundbox',
        name: 'Fundbox',
        categoryId: 'lending',
        websiteUrl: 'https://fundbox.com',
        affiliateStatus: 'none',
        tagline: 'Business line of credit with quick approval',
        desc: 'Small business line of credit with fast approval based on business bank account data. Designed for contractors who need short-term cash flow support. Draws repaid over 12 or 24 weeks.',
        costLevel: 'medium',
        costNote: 'Rates from 4.66% for 12-week repayment',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Approval based on cash flow history, not just credit score',
        integrates: ['quickbooks'],
        freeOption: false,
      },
      {
        id: 'sba-loans',
        name: 'SBA Loans (via local bank)',
        categoryId: 'lending',
        websiteUrl: 'https://www.sba.gov/funding-programs/loans',
        affiliateStatus: 'none',
        tagline: 'Government-backed loans for small business growth',
        desc: 'SBA 7(a) and 504 loans offer the lowest-rate long-term financing available to small contractors. 7(a) for working capital and equipment; 504 for commercial real estate and large equipment. Apply through SBA-approved lenders (Chase, Wells Fargo, local banks).',
        costLevel: 'low',
        costNote: 'Rates tied to prime; typically Prime + 2.25–4.75% depending on loan size and term',
        setupDifficulty: 'advanced',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Lowest available rates for equipment purchase, expansion, or real estate for contractors',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'nav',
        name: 'Nav',
        categoryId: 'lending',
        websiteUrl: 'https://www.nav.com',
        affiliateStatus: 'active',
        tagline: 'Monitor business credit and find the right financing',
        desc: 'Business credit monitoring and loan marketplace. Contractors use Nav to track their business Dun & Bradstreet, Equifax, and Experian business credit scores and find lending products matched to their profile.',
        costLevel: 'free',
        costNote: 'Free credit monitoring; premium plans $49–$199/month',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Business credit score monitoring across all three bureaus in one dashboard',
        integrates: [],
        freeOption: true,
      },
      {
        id: 'lendio',
        name: 'Lendio',
        categoryId: 'lending',
        websiteUrl: 'https://www.lendio.com',
        affiliateStatus: 'none',
        tagline: 'Small business loan marketplace for contractors',
        desc: 'Loan marketplace that matches contractors to multiple lenders with a single application. Useful for contractors who have been turned down by a bank or want to compare SBA, equipment, and line-of-credit options side by side.',
        costLevel: 'free',
        costNote: 'Free to apply; lender fees apply to funded loans',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Single application compared across 75+ lenders — no guessing which bank to approach first',
        integrates: [],
        freeOption: true,
      },
    ],
  },

  {
    id: 'reviews',
    label: 'Review Management',
    shortLabel: 'Reviews',
    icon: '⭐',
    description: 'Platforms for collecting, managing, and responding to customer reviews.',
    whyItMatters: 'Reviews drive local search ranking and customer trust. A systematic review collection process is the highest-ROI reputation investment a contractor can make.',
    phaseRelevance: ['followup-reviews-reputation', 'lead-flow-visibility'],
    vendors: [
      {
        id: 'podium',
        name: 'Podium',
        categoryId: 'reviews',
        websiteUrl: 'https://www.podium.com',
        affiliateStatus: 'active',
        tagline: 'Customer messaging, reviews, and payments in one platform',
        desc: 'All-in-one customer communication platform with automated review requests, text marketing, webchat, and payment collection. Most comprehensive review management tool for established contractors.',
        costLevel: 'high',
        costNote: 'Starts at $399/month for Core plan',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Automated multi-channel review request with response tracking across platforms',
        integrates: ['jobber', 'housecall-pro', 'servicetitan'],
        freeOption: false,
      },
      {
        id: 'nicejob',
        name: 'NiceJob',
        categoryId: 'reviews',
        websiteUrl: 'https://nicejob.com',
        affiliateStatus: 'none',
        tagline: 'Automated review and referral platform for contractors',
        desc: 'Purpose-built review automation for home service businesses. Automated post-job review requests, referral campaigns, and social sharing. Lower cost than Podium with a focus on review collection workflow.',
        costLevel: 'low',
        costNote: 'Starts at $75/month',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Automated review + referral follow-up in a single post-job sequence',
        integrates: ['jobber', 'housecall-pro', 'zapier'],
        freeOption: false,
      },
      {
        id: 'birdeye',
        name: 'Birdeye',
        categoryId: 'reviews',
        websiteUrl: 'https://birdeye.com',
        affiliateStatus: 'none',
        tagline: 'Multi-location reputation management',
        desc: 'Reputation management and customer experience platform. Best for contractors with multiple locations who need centralized review tracking and response management across all properties.',
        costLevel: 'high',
        costNote: 'Starts at $299/month per location',
        setupDifficulty: 'moderate',
        bestFor: ['scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Multi-location review management with AI response suggestions',
        integrates: ['salesforce', 'hubspot', 'zapier'],
        freeOption: false,
      },
    ],
  },

  {
    id: 'phones',
    label: 'Business Phone Systems',
    shortLabel: 'Phones',
    icon: '📞',
    description: 'Business phone systems, VoIP, and call management tools for contractors.',
    whyItMatters: 'A professional business phone system with tracking, recording, and missed call management is essential infrastructure for any contractor serious about lead conversion.',
    phaseRelevance: ['sales-process-call-handling'],
    vendors: [
      {
        id: 'openphone',
        name: 'OpenPhone',
        categoryId: 'phones',
        websiteUrl: 'https://www.openphone.com',
        affiliateStatus: 'none',
        tagline: 'Business phone number with shared team inbox',
        desc: 'VoIP business phone system with shared inbox, call recording, and text messaging. Good for solo contractors and small teams who want a professional business number separate from their personal phone.',
        costLevel: 'low',
        costNote: 'Starts at $13/user/month',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Shared team inbox so calls and texts are visible to the whole office team',
        integrates: ['hubspot', 'zapier'],
        freeOption: false,
      },
      {
        id: 'ringcentral',
        name: 'RingCentral',
        categoryId: 'phones',
        websiteUrl: 'https://www.ringcentral.com',
        affiliateStatus: 'none',
        tagline: 'Business phone, video, and messaging platform',
        desc: 'Enterprise VoIP and UCaaS platform. Handles calls, SMS, video meetings, and team messaging. More capability than most small contractors need, but ideal for multi-location or larger operations with complex call routing.',
        costLevel: 'medium',
        costNote: 'Starts at $20/user/month for Core',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Advanced call routing, IVR, and analytics for multi-tech operations',
        integrates: ['salesforce', 'google', 'microsoft'],
        freeOption: false,
      },
      {
        id: 'callrail-phone',
        name: 'CallRail',
        categoryId: 'phones',
        websiteUrl: 'https://www.callrail.com',
        affiliateStatus: 'none',
        tagline: 'Call tracking and analytics for marketing attribution',
        desc: 'Call tracking platform that assigns unique numbers to each marketing channel (Google Ads, Angi, yard signs, etc.) and tracks which source generated the call. Essential for contractors spending on multiple marketing channels.',
        costLevel: 'low',
        costNote: 'Starts at $45/month for call tracking',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Granular call attribution showing revenue per marketing channel',
        integrates: ['google-ads', 'google-analytics', 'hubspot'],
        freeOption: false,
      },
    ],
  },

  {
    id: 'websites-seo',
    label: 'Websites & Local SEO',
    shortLabel: 'Web/SEO',
    icon: '🌐',
    description: 'Website development and local SEO services for contractors.',
    whyItMatters: 'A professional website with local SEO optimization is the anchor of organic lead generation. It is where customers verify your credibility and where Google sends local service search traffic.',
    phaseRelevance: ['lead-flow-visibility'],
    vendors: [
      {
        id: 'scorpion',
        name: 'Scorpion',
        categoryId: 'websites-seo',
        websiteUrl: 'https://www.scorpion.co',
        affiliateStatus: 'none',
        tagline: 'Marketing and websites built for home service companies',
        desc: 'Full-service digital marketing agency specializing in home services. Builds contractor websites, manages local SEO, Google Ads, and LSA campaigns. Premium service with performance guarantees.',
        costLevel: 'high',
        costNote: 'Custom pricing; typically $1,500–$3,000+/month for full service',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'plumbing', 'electrical'],
        standoutFeature: 'Integrated marketing platform with revenue attribution reporting',
        integrates: ['servicetitan', 'jobber'],
        freeOption: false,
      },
      {
        id: 'ryno',
        name: 'RYNO Strategic Solutions',
        categoryId: 'websites-seo',
        websiteUrl: 'https://www.rynoss.com',
        affiliateStatus: 'none',
        tagline: 'Digital marketing for HVAC, plumbing, and electrical',
        desc: 'Contractor-specific digital marketing agency focused on organic SEO, Google Ads, and website performance. Known in the trades industry for deep trade expertise and realistic ROI tracking.',
        costLevel: 'high',
        costNote: 'Custom pricing; typically $1,000–$3,000+/month',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'plumbing', 'electrical'],
        standoutFeature: 'Deep trades industry knowledge — built campaigns for 500+ HVAC and plumbing companies',
        integrates: ['servicetitan'],
        freeOption: false,
      },
      {
        id: 'broadly',
        name: 'Broadly',
        categoryId: 'websites-seo',
        websiteUrl: 'https://broadly.com',
        affiliateStatus: 'active',
        tagline: 'Reputation and web presence for local home service businesses',
        desc: 'Combines review management, customer messaging, and basic web presence management for home service contractors. Good value for smaller contractors who want review automation and simple web updates in one tool.',
        costLevel: 'medium',
        costNote: 'Custom pricing; typically $200–$400/month',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Review automation combined with webchat and basic customer messaging',
        integrates: ['jobber', 'housecall-pro'],
        freeOption: false,
      },
      {
        id: 'google-business-profile',
        name: 'Google Business Profile',
        categoryId: 'websites-seo',
        websiteUrl: 'https://business.google.com',
        affiliateStatus: 'none',
        tagline: 'Free local business listing on Google Search and Maps',
        desc: 'The single most important free marketing tool for residential contractors. A fully optimized Google Business Profile drives local search visibility, review collection, phone calls, and directions requests. Setup takes under an hour.',
        costLevel: 'free',
        costNote: 'Completely free to claim and manage',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early', 'growth', 'scale', 'any'],
        tradeRelevance: ['all'],
        standoutFeature: 'Highest-ROI free tool available — directly drives local calls and job leads',
        integrates: [],
        freeOption: true,
      },
    ],
  },

  {
    id: 'social-design',
    label: 'Social Media & Design',
    shortLabel: 'Social/Design',
    icon: '🎨',
    description: 'Tools for creating branded content, managing social media, and building online brand presence.',
    whyItMatters: 'Consistent, professional brand content on social media builds awareness with customers before they need you and keeps you top-of-mind when they do.',
    phaseRelevance: ['brand-social-media'],
    vendors: [
      {
        id: 'canva',
        name: 'Canva',
        categoryId: 'social-design',
        websiteUrl: 'https://www.canva.com',
        affiliateStatus: 'none',
        tagline: 'Easy graphic design for social posts, flyers, and brand assets',
        desc: 'Free-to-use graphic design platform with contractor-friendly templates for social posts, flyers, business cards, truck wrap concepts, and email headers. The standard tool for contractors creating their own marketing assets.',
        costLevel: 'free',
        costNote: 'Free for most features; Canva Pro at $15/month adds brand kit and premium templates',
        setupDifficulty: 'easy',
        bestFor: ['any'],
        tradeRelevance: ['all'],
        standoutFeature: 'Thousands of contractor-relevant templates ready to customize with your brand',
        integrates: ['google-drive', 'dropbox'],
        freeOption: true,
      },
      {
        id: 'buffer',
        name: 'Buffer',
        categoryId: 'social-design',
        websiteUrl: 'https://buffer.com',
        affiliateStatus: 'none',
        tagline: 'Schedule and manage social media posts across platforms',
        desc: 'Simple social media scheduling tool for Facebook, Instagram, LinkedIn, and Google Business Profile. Schedule a week of posts in one sitting. Free tier covers most contractor needs.',
        costLevel: 'free',
        costNote: 'Free for 3 channels and 10 scheduled posts; $6/month per channel for more',
        setupDifficulty: 'easy',
        bestFor: ['any'],
        tradeRelevance: ['all'],
        standoutFeature: 'Post once, publish to all platforms simultaneously with one schedule',
        integrates: ['canva'],
        freeOption: true,
      },
      {
        id: 'capcut',
        name: 'CapCut',
        categoryId: 'social-design',
        websiteUrl: 'https://www.capcut.com',
        affiliateStatus: 'none',
        tagline: 'Free video editor for Reels and short-form content',
        desc: 'Free mobile and desktop video editing app. Contractors use it to edit phone-recorded before/after clips into professional-looking Reels and TikToks. Auto-captions, music, and templates included.',
        costLevel: 'free',
        costNote: 'Free for most features',
        setupDifficulty: 'easy',
        bestFor: ['any'],
        tradeRelevance: ['all'],
        standoutFeature: 'Auto-captioning and phone-to-Reel workflow in under 5 minutes',
        integrates: ['instagram', 'tiktok'],
        freeOption: true,
      },
      {
        id: 'metricool',
        name: 'Metricool',
        categoryId: 'social-design',
        websiteUrl: 'https://metricool.com',
        affiliateStatus: 'none',
        tagline: 'Social media scheduler and analytics for small businesses',
        desc: 'All-in-one social media planning, scheduling, and analytics tool. Contractors use it to schedule posts across Facebook, Instagram, Google Business Profile, and LinkedIn from one dashboard. Cleaner analytics than Buffer.',
        costLevel: 'free',
        costNote: 'Free for 1 brand and basic scheduling; paid plans start at $22/month',
        setupDifficulty: 'easy',
        bestFor: ['any'],
        tradeRelevance: ['all'],
        standoutFeature: 'Google Business Profile scheduling built in — rare among social tools',
        integrates: ['canva', 'google-business-profile'],
        freeOption: true,
      },
      {
        id: 'adobe-express',
        name: 'Adobe Express',
        categoryId: 'social-design',
        websiteUrl: 'https://www.adobe.com/express/',
        affiliateStatus: 'none',
        tagline: 'Quick graphic and video creation for social content',
        desc: 'Adobe\'s simplified content creation tool for social posts, flyers, and short videos. Free tier includes templates, basic design tools, and Adobe Stock access. Good Canva alternative for contractors already in the Adobe ecosystem.',
        costLevel: 'free',
        costNote: 'Free with limited features; included with Adobe Creative Cloud subscriptions',
        setupDifficulty: 'easy',
        bestFor: ['any'],
        tradeRelevance: ['all'],
        standoutFeature: 'Quick-start templates and brand kit for consistent contractor marketing materials',
        integrates: ['google-drive', 'dropbox'],
        freeOption: true,
      },
    ],
  },

  {
    id: 'email-sms',
    label: 'Email & SMS Marketing',
    shortLabel: 'Email/SMS',
    icon: '📧',
    description: 'Email and text marketing platforms for customer communication and seasonal campaigns.',
    whyItMatters: 'Your past customer list is your most valuable marketing asset. Email and SMS campaigns to existing customers cost nearly nothing and generate immediate jobs.',
    phaseRelevance: ['followup-reviews-reputation', 'lead-flow-visibility'],
    vendors: [
      {
        id: 'mailchimp',
        name: 'Mailchimp',
        categoryId: 'email-sms',
        websiteUrl: 'https://mailchimp.com',
        affiliateStatus: 'active',
        tagline: 'Email marketing for small businesses',
        desc: 'The most widely used email marketing platform. Good for contractors sending seasonal promotions, newsletter updates, or maintenance reminders to past customers. Free tier up to 500 contacts.',
        costLevel: 'free',
        costNote: 'Free up to 500 contacts/1,000 sends per month; paid plans start at $13/month',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Free tier covers most contractor needs; simple automation for seasonal campaigns',
        integrates: ['housecall-pro', 'google', 'zapier'],
        freeOption: true,
      },
      {
        id: 'constant-contact',
        name: 'Constant Contact',
        categoryId: 'email-sms',
        websiteUrl: 'https://www.constantcontact.com',
        affiliateStatus: 'none',
        tagline: 'Email and SMS marketing for small businesses',
        desc: 'Email and text marketing combined platform. Better SMS capability than Mailchimp. Good for contractors who want to send maintenance reminders or seasonal promotions via both email and text.',
        costLevel: 'low',
        costNote: 'Starts at $12/month for email; SMS add-on available',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Combined email and SMS in one platform with strong support',
        integrates: ['shopify', 'eventbrite', 'zapier'],
        freeOption: false,
      },
      {
        id: 'text-request',
        name: 'Text Request',
        categoryId: 'email-sms',
        websiteUrl: 'https://www.textrequest.com',
        affiliateStatus: 'none',
        tagline: 'Business texting for appointment reminders and follow-up',
        desc: 'SMS texting platform built for service businesses. Send appointment reminders, follow-up texts, and promotions from a business number. Higher open rates than email make it effective for same-day scheduling and re-engagement.',
        costLevel: 'low',
        costNote: 'Starts at $59/month for up to 1,000 messages',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Landline texting — send SMS from your existing business phone number',
        integrates: ['zapier'],
        freeOption: false,
      },
      {
        id: 'slicktext',
        name: 'SlickText',
        categoryId: 'email-sms',
        websiteUrl: 'https://www.slicktext.com',
        affiliateStatus: 'none',
        tagline: 'SMS marketing and automated text campaigns',
        desc: 'SMS marketing platform for broadcast texts, maintenance reminders, and seasonal campaigns. Good for contractors building a customer text list for recurring service outreach and promotional blasts.',
        costLevel: 'low',
        costNote: 'Starts at $29/month for 500 texts; scales by volume',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Keyword opt-in campaigns and automated drip sequences for service follow-up',
        integrates: ['zapier', 'mailchimp'],
        freeOption: false,
      },
    ],
  },

  {
    id: 'automation',
    label: 'Automation & Integration',
    shortLabel: 'Automation',
    icon: '⚡',
    description: 'Tools that connect your apps and automate repetitive workflows.',
    whyItMatters: 'Automation eliminates manual data entry, follow-up tasks, and process gaps between systems. Every hour saved on admin is an hour that can be spent on billable work.',
    phaseRelevance: ['dispatch-scheduling-workflow', 'scaling-hiring-leadership'],
    vendors: [
      {
        id: 'zapier',
        name: 'Zapier',
        categoryId: 'automation',
        websiteUrl: 'https://zapier.com',
        affiliateStatus: 'none',
        tagline: 'Connect your apps and automate workflows without code',
        desc: 'No-code automation platform that connects 5,000+ apps. Contractors use it to sync FSM data to CRM, trigger follow-up emails from Jobber, or push new leads from web forms to their CRM automatically.',
        costLevel: 'free',
        costNote: 'Free for 100 tasks/month; paid starts at $19.99/month for more tasks',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Connect any two apps that do not natively integrate — 5,000+ app library',
        integrates: ['jobber', 'housecall-pro', 'quickbooks', 'mailchimp', 'hubspot'],
        freeOption: true,
      },
      {
        id: 'make-com',
        name: 'Make (formerly Integromat)',
        categoryId: 'automation',
        websiteUrl: 'https://www.make.com',
        affiliateStatus: 'none',
        tagline: 'Visual workflow automation more powerful than Zapier',
        desc: 'More complex automation scenarios than Zapier, with better pricing for high-volume workflows. Popular for contractors with more sophisticated data flows between FSM, CRM, and accounting platforms.',
        costLevel: 'free',
        costNote: 'Free for 1,000 operations/month; paid starts at $9/month',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Complex multi-step workflows with conditional logic at lower cost than Zapier',
        integrates: ['google-sheets', 'airtable', 'quickbooks', 'stripe'],
        freeOption: true,
      },
    ],
  },

  {
    id: 'documentation',
    label: 'Documentation & Field Forms',
    shortLabel: 'Docs/Forms',
    icon: '📝',
    description: 'Job photo documentation, digital forms, safety checklists, and field reporting tools.',
    whyItMatters: 'Photo documentation protects against liability disputes, supports upsell recommendations, and builds a professional record of every job. Digital forms replace paper and create searchable job records.',
    phaseRelevance: ['technician-performance', 'dispatch-scheduling-workflow'],
    vendors: [
      {
        id: 'companycam',
        name: 'CompanyCam',
        categoryId: 'documentation',
        websiteUrl: 'https://companycam.com',
        affiliateStatus: 'none',
        tagline: 'Job photo documentation for field service companies',
        desc: 'Photo documentation platform purpose-built for contractors. Techs upload job photos that are automatically tagged to the job address, organized by date, and accessible to the office in real time. Standard for roofing, HVAC, and general contracting.',
        costLevel: 'low',
        costNote: 'Starts at $24/user/month',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Automatic GPS-tagged photo organization by job address — no filing required',
        integrates: ['jobber', 'housecall-pro', 'servicetitan', 'microsoft-teams'],
        freeOption: false,
      },
      {
        id: 'jotform',
        name: 'JotForm',
        categoryId: 'documentation',
        websiteUrl: 'https://www.jotform.com',
        affiliateStatus: 'none',
        tagline: 'Digital forms and checklists for field operations',
        desc: 'Form builder used by contractors for service agreements, safety checklists, inspection reports, and employee onboarding forms. Submissions stored digitally and can trigger email notifications.',
        costLevel: 'free',
        costNote: 'Free for 5 forms and 100 submissions/month; paid starts at $39/month',
        setupDifficulty: 'easy',
        bestFor: ['any'],
        tradeRelevance: ['all'],
        standoutFeature: 'Pre-built contractor form templates including service agreements and safety forms',
        integrates: ['google-drive', 'dropbox', 'zapier'],
        freeOption: true,
      },
      {
        id: 'safetyculture',
        name: 'SafetyCulture (iAuditor)',
        categoryId: 'documentation',
        websiteUrl: 'https://safetyculture.com',
        affiliateStatus: 'none',
        tagline: 'Safety checklists and inspection forms for field teams',
        desc: 'Safety inspection and checklist platform. Contractors use it for job site safety audits, equipment inspections, and compliance documentation. Required by some commercial clients and insurance programs.',
        costLevel: 'free',
        costNote: 'Free for up to 10 users with basic features; paid plans from $24/user/month',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['construction', 'electrical', 'hvac', 'plumbing'],
        standoutFeature: 'OSHA-aligned safety inspection templates and audit reporting',
        integrates: ['zapier', 'microsoft-365'],
        freeOption: true,
      },
    ],
  },

  {
    id: 'training',
    label: 'Trade Training & Education',
    shortLabel: 'Training',
    icon: '🎓',
    description: 'Technical and business training platforms for contractors and technicians.',
    whyItMatters: 'Trained technicians produce higher quality work, close more upsells, and generate fewer callbacks. Continuous training is a competitive advantage in a market with a tech shortage.',
    phaseRelevance: ['technician-performance', 'scaling-hiring-leadership'],
    vendors: [
      {
        id: 'interplay-learning',
        name: 'Interplay Learning',
        categoryId: 'training',
        websiteUrl: 'https://www.interplaylearning.com',
        affiliateStatus: 'none',
        tagline: '3D simulation training for HVAC, electrical, and plumbing',
        desc: 'Online and simulation-based technical training for HVAC, electrical, plumbing, and other trades. Used by contractors for tech onboarding, skills gap training, and apprentice development. NATE-approved content.',
        costLevel: 'medium',
        costNote: 'Starts at $99/month for team access',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'electrical', 'plumbing'],
        standoutFeature: '3D interactive simulation training — techs learn by doing, not just watching',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'skillcat',
        name: 'SkillCat',
        categoryId: 'training',
        websiteUrl: 'https://www.skillcat.com',
        affiliateStatus: 'none',
        tagline: 'Mobile-first certification training for trade techs',
        desc: 'Mobile-first training platform for HVAC EPA 608, NATE, and other certifications. Used by contractors for new tech certification prep and recertification. More affordable than Interplay for certification-only needs.',
        costLevel: 'low',
        costNote: 'EPA 608 certification training for $29; team plans available',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early', 'growth'],
        tradeRelevance: ['hvac'],
        standoutFeature: 'Affordable EPA 608 and NATE certification prep on mobile',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'bdr-training',
        name: 'BDR (Business Development Resources)',
        categoryId: 'training',
        websiteUrl: 'https://www.bdrco.com',
        affiliateStatus: 'none',
        tagline: 'Sales and business training for home service contractors',
        desc: 'Contractor-specific sales training, coaching, and business development programs. BDR focuses on technician sales skills, CSR phone training, and owner/manager leadership development. Well-known in HVAC and plumbing industries.',
        costLevel: 'high',
        costNote: 'Training programs and workshops vary; typically $500–$3,000+ per program',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'plumbing', 'electrical'],
        standoutFeature: 'Field-tested sales scripts and CSR phone training purpose-built for trades',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'nexstar-network',
        name: 'Nexstar Network',
        categoryId: 'training',
        websiteUrl: 'https://www.nexstarnetwork.com',
        affiliateStatus: 'none',
        tagline: 'Business coaching and peer groups for service contractors',
        desc: 'The leading business coaching and peer group network for home service contractors. Nexstar members outperform industry averages on revenue, profitability, and employee retention. Coaching, workshops, and benchmarking.',
        costLevel: 'enterprise',
        costNote: 'Membership fees vary; typically $2,000–$5,000+/month',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'plumbing', 'electrical'],
        standoutFeature: 'Industry-specific peer benchmarking and structured coaching accountability',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'service-nation',
        name: 'Service Nation',
        categoryId: 'training',
        websiteUrl: 'https://servicenation.com',
        affiliateStatus: 'none',
        tagline: 'Peer groups and business training for home service contractors',
        desc: 'Business development organization with peer groups, industry benchmarking, and training programs for residential service contractors. Members gain access to performance data, best practices, and structured coaching accountability.',
        costLevel: 'enterprise',
        costNote: 'Membership fees vary; contact for current pricing',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'plumbing', 'electrical'],
        standoutFeature: 'Peer group accountability with industry benchmarking data for residential contractors',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'certainpath',
        name: 'CertainPath',
        categoryId: 'training',
        websiteUrl: 'https://certainpath.com',
        affiliateStatus: 'none',
        tagline: 'Business coaching and systems for trades contractors',
        desc: 'Formerly EGIA Contractor University. Structured business coaching, training, and peer groups for HVAC, plumbing, and electrical contractors. Strong focus on flat-rate pricing, sales process, and operational systems.',
        costLevel: 'enterprise',
        costNote: 'Membership and coaching programs vary; contact for pricing',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['hvac', 'plumbing', 'electrical'],
        standoutFeature: 'Structured business systems curriculum — pricing, sales, and operations built for trades',
        integrates: [],
        freeOption: false,
      },
    ],
  },

  {
    id: 'fleet-gps',
    label: 'Fleet & GPS Tracking',
    shortLabel: 'Fleet/GPS',
    icon: '🚛',
    description: 'Vehicle tracking and fleet management systems for contractor fleets.',
    whyItMatters: 'GPS tracking reduces unauthorized vehicle use, improves dispatch accuracy, and provides liability protection in the event of an accident. Required by some commercial contracts.',
    phaseRelevance: ['dispatch-scheduling-workflow'],
    vendors: [
      {
        id: 'samsara',
        name: 'Samsara',
        categoryId: 'fleet-gps',
        websiteUrl: 'https://www.samsara.com',
        affiliateStatus: 'none',
        tagline: 'GPS tracking and dash cams for contractor fleets',
        desc: 'Fleet management platform with GPS tracking, dash cameras, driver safety scoring, and maintenance alerts. Used by larger contractor fleets for dispatch optimization and driver accountability.',
        costLevel: 'medium',
        costNote: 'Hardware cost + subscription; typically $25–$45/vehicle/month',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'AI dash cam with incident detection and driver coaching alerts',
        integrates: ['servicetitan'],
        freeOption: false,
      },
      {
        id: 'motive',
        name: 'Motive (formerly KeepTruckin)',
        categoryId: 'fleet-gps',
        websiteUrl: 'https://gomotive.com',
        affiliateStatus: 'none',
        tagline: 'GPS and fleet management for contractors and fleets',
        desc: 'GPS tracking, dash cam, and fleet management platform. Strong for contractors managing multiple vehicles and needing fuel card integration, maintenance scheduling, and dispatch analytics.',
        costLevel: 'medium',
        costNote: 'Hardware + subscription; typically $20–$35/vehicle/month',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Integrated fuel card management and maintenance scheduling',
        integrates: ['quickbooks'],
        freeOption: false,
      },
      {
        id: 'verizon-connect',
        name: 'Verizon Connect',
        categoryId: 'fleet-gps',
        websiteUrl: 'https://www.verizonconnect.com',
        affiliateStatus: 'none',
        tagline: 'Enterprise fleet tracking and field workforce management',
        desc: 'Enterprise fleet management with GPS tracking, route optimization, and job dispatching. More comprehensive than Samsara for contractors who want combined dispatch and fleet management.',
        costLevel: 'high',
        costNote: 'Custom pricing; typically $35–$70/vehicle/month',
        setupDifficulty: 'advanced',
        bestFor: ['scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Combined fleet management and field service dispatching in one platform',
        integrates: ['servicetitan'],
        freeOption: false,
      },
      {
        id: 'wex-fleet',
        name: 'WEX Fleet Card',
        categoryId: 'fleet-gps',
        websiteUrl: 'https://www.wexinc.com/products/fleet-cards',
        affiliateStatus: 'none',
        tagline: 'Fleet fuel cards with spending controls for contractor vehicles',
        desc: 'Dedicated fleet fuel card that controls what drivers can purchase, tracks fuel spend by vehicle, and generates reports for bookkeeping. Reduces unauthorized personal purchases and simplifies fuel expense tracking across a fleet.',
        costLevel: 'free',
        costNote: 'No monthly fee; transaction fees may apply depending on program',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Per-vehicle spending controls that block personal purchases at the pump',
        integrates: ['quickbooks'],
        freeOption: true,
      },
      {
        id: 'fuelman',
        name: 'Fuelman',
        categoryId: 'fleet-gps',
        websiteUrl: 'https://www.fuelman.com',
        affiliateStatus: 'none',
        tagline: 'Fleet fuel card network for small and mid-size fleets',
        desc: 'Fleet fuel card with broad station acceptance, purchase controls, and reporting for small contractor fleets. Includes driver ID PINs, odometer tracking, and monthly reporting for fleet fuel cost management.',
        costLevel: 'free',
        costNote: 'No monthly fee; fees apply based on transaction volume',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Driver PIN-based purchase verification and broad station network acceptance',
        integrates: [],
        freeOption: true,
      },
    ],
  },

  {
    id: 'formation-legal',
    label: 'Business Formation & Legal',
    shortLabel: 'Formation',
    icon: '⚖️',
    description: 'LLC formation, registered agent, and business legal services.',
    whyItMatters: 'Proper business formation creates legal liability separation, enables business banking, and is required for most licensing and bonding applications.',
    phaseRelevance: ['foundation-setup'],
    vendors: [
      {
        id: 'zenbusiness',
        name: 'ZenBusiness',
        categoryId: 'formation-legal',
        websiteUrl: 'https://www.zenbusiness.com',
        affiliateStatus: 'active',
        tagline: 'Fast, affordable LLC formation and registered agent',
        desc: 'LLC and corporation formation service with registered agent, operating agreement, and EIN obtainment. Good value for contractors who want guided formation without a full attorney cost.',
        costLevel: 'low',
        costNote: 'Starter plan $0 + state fee; Pro at $199/year with registered agent',
        setupDifficulty: 'easy',
        bestFor: ['startup'],
        tradeRelevance: ['all'],
        standoutFeature: 'Guided formation with registered agent included in most plans',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'northwest-ra',
        name: 'Northwest Registered Agent',
        categoryId: 'formation-legal',
        websiteUrl: 'https://www.northwestregisteredagent.com',
        affiliateStatus: 'none',
        tagline: 'Privacy-first registered agent and LLC formation',
        desc: 'Registered agent service with strong privacy protections. All formation documents list Northwest\'s address instead of the owner\'s personal address — preferred by contractors working from home.',
        costLevel: 'low',
        costNote: '$125/year for registered agent service; formation service available',
        setupDifficulty: 'easy',
        bestFor: ['startup'],
        tradeRelevance: ['all'],
        standoutFeature: 'Home address privacy protection — their address on your public filings',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'legalzoom',
        name: 'LegalZoom',
        categoryId: 'formation-legal',
        websiteUrl: 'https://www.legalzoom.com',
        affiliateStatus: 'none',
        tagline: 'Legal documents and business formation for small businesses',
        desc: 'Legal document preparation and business formation service. Broader document library than ZenBusiness — useful for contractors who also need operating agreements, service contracts, or employment agreements.',
        costLevel: 'medium',
        costNote: 'Formation from $79 + state fee; attorney consultation plans available',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early'],
        tradeRelevance: ['all'],
        standoutFeature: 'Broader legal document library including contracts and employment agreements',
        integrates: [],
        freeOption: false,
      },
    ],
  },

  {
    id: 'hiring-recruiting',
    label: 'Hiring & Recruiting',
    shortLabel: 'Hiring',
    icon: '🤝',
    description: 'Job boards, hiring platforms, and recruiting tools for finding qualified tradespeople.',
    whyItMatters: 'Finding skilled techs and field staff is one of the biggest growth bottlenecks in the trades. A consistent hiring pipeline matters as much as a sales pipeline.',
    phaseRelevance: ['scaling-hiring-leadership', 'technician-performance'],
    vendors: [
      {
        id: 'indeed',
        name: 'Indeed',
        categoryId: 'hiring-recruiting',
        websiteUrl: 'https://www.indeed.com/hire',
        affiliateStatus: 'none',
        tagline: 'The largest job board for finding trade workers',
        desc: 'The most widely used job board for finding field technicians, installers, and trade helpers. Contractors post jobs and review applications. Sponsored postings increase visibility. Free to post; pay-per-click for featured placement.',
        costLevel: 'free',
        costNote: 'Free job posting; sponsored listings typically $5–$15/day per post',
        setupDifficulty: 'easy',
        bestFor: ['early', 'growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Largest candidate pool for trade job postings — most applications per post',
        integrates: [],
        freeOption: true,
      },
      {
        id: 'ziprecruiter',
        name: 'ZipRecruiter',
        categoryId: 'hiring-recruiting',
        websiteUrl: 'https://www.ziprecruiter.com/employers',
        affiliateStatus: 'none',
        tagline: 'Automated job distribution to 100+ job boards',
        desc: 'Posts jobs to over 100 job sites from one dashboard and uses AI matching to surface qualified candidates. Contractors get more applications faster than a single-board post. Good for scaling businesses hiring multiple positions.',
        costLevel: 'medium',
        costNote: 'Starts at $299/month for unlimited job posts',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'One post reaches 100+ job boards simultaneously — faster to fill open positions',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'linkedin-jobs',
        name: 'LinkedIn Jobs',
        categoryId: 'hiring-recruiting',
        websiteUrl: 'https://www.linkedin.com/talent',
        affiliateStatus: 'none',
        tagline: 'Professional hiring for foremen, estimators, and office roles',
        desc: 'Better for hiring office staff, project managers, estimators, and foremen than for field technicians. LinkedIn reaches candidates who are already employed — useful for recruiting experienced trade professionals rather than entry-level workers.',
        costLevel: 'medium',
        costNote: 'Job posts start free for limited visibility; promoted posts from $5–$15/day',
        setupDifficulty: 'easy',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Reaches working professionals — best for estimators, PMs, and foreman-level hires',
        integrates: [],
        freeOption: true,
      },
    ],
  },

  {
    id: 'local-ads',
    label: 'Local Advertising & Lead Sources',
    shortLabel: 'Local Ads',
    icon: '📍',
    description: 'Paid advertising and lead generation platforms for local contractor visibility.',
    whyItMatters: 'Organic SEO and referrals build long-term leads, but paid local advertising fills the calendar now. Google Local Services Ads is the highest-ROI paid channel for most residential contractors.',
    phaseRelevance: ['lead-flow-visibility', 'brand-social-media'],
    vendors: [
      {
        id: 'google-lsa',
        name: 'Google Local Services Ads',
        categoryId: 'local-ads',
        websiteUrl: 'https://ads.google.com/local-services-ads',
        affiliateStatus: 'none',
        tagline: 'Pay-per-lead ads that appear above Google search results',
        desc: 'Google-verified contractor ads that appear at the very top of search results. You pay per lead, not per click. Requires background check and license verification — the Google Guarantee badge improves customer conversion.',
        costLevel: 'medium',
        costNote: 'Pay-per-lead; typical cost $15–$80/lead depending on trade and market',
        setupDifficulty: 'moderate',
        bestFor: ['early', 'growth', 'scale'],
        tradeRelevance: ['hvac', 'plumbing', 'electrical', 'roofing', 'construction'],
        standoutFeature: 'Google Guarantee badge and pay-per-lead model — only pay when a customer contacts you',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'google-ads',
        name: 'Google Search Ads',
        categoryId: 'local-ads',
        websiteUrl: 'https://ads.google.com',
        affiliateStatus: 'none',
        tagline: 'Paid search ads targeting local homeowners actively searching',
        desc: 'Pay-per-click search advertising targeting homeowners searching for contractor services in your area. More control than LSA but requires active bid management and a conversion-ready landing page. Best managed by a trade-specialized agency.',
        costLevel: 'high',
        costNote: 'Budget-dependent; trade keywords typically $8–$40/click depending on market',
        setupDifficulty: 'advanced',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Precise targeting by keyword, location radius, and time of day',
        integrates: ['callrail'],
        freeOption: false,
      },
      {
        id: 'meta-ads',
        name: 'Meta Ads (Facebook/Instagram)',
        categoryId: 'local-ads',
        websiteUrl: 'https://www.facebook.com/business/ads',
        affiliateStatus: 'none',
        tagline: 'Targeted local ads for brand awareness and homeowner outreach',
        desc: 'Facebook and Instagram advertising for reaching homeowners in a specific geography. Less intent-based than Google but effective for brand awareness, seasonal promotions, and retargeting past visitors.',
        costLevel: 'medium',
        costNote: 'Budget-dependent; typical starting campaigns $300–$500/month',
        setupDifficulty: 'moderate',
        bestFor: ['growth', 'scale'],
        tradeRelevance: ['all'],
        standoutFeature: 'Demographic targeting by homeowner status, income, and neighborhood',
        integrates: [],
        freeOption: false,
      },
      {
        id: 'angi-pro',
        name: 'Angi Pro',
        categoryId: 'local-ads',
        websiteUrl: 'https://pro.angi.com',
        affiliateStatus: 'none',
        tagline: 'Lead marketplace connecting homeowners to local contractors',
        desc: 'Lead generation marketplace formerly known as Angie\'s List and HomeAdvisor. Contractors pay for shared or exclusive leads from homeowners actively requesting service. High lead volume but shared leads require fast response to compete.',
        costLevel: 'medium',
        costNote: 'Lead prices vary by trade and market; typically $15–$80/lead',
        setupDifficulty: 'easy',
        bestFor: ['startup', 'early', 'growth'],
        tradeRelevance: ['all'],
        standoutFeature: 'Large homeowner demand network — high volume of leads in most markets',
        integrates: [],
        freeOption: false,
      },
    ],
  },
]

// ── Helpers ────────────────────────────────────────────────────────────────────

export function getVendorById(id: string): VendorEntry | undefined {
  for (const cat of VENDOR_CATEGORIES) {
    const found = cat.vendors.find(v => v.id === id)
    if (found) return found
  }
  return undefined
}

export function getVendorsByCategory(categoryId: string): VendorEntry[] {
  return VENDOR_CATEGORIES.find(c => c.id === categoryId)?.vendors ?? []
}

export function getVendorsForPhase(vendorIds: string[]): VendorEntry[] {
  return vendorIds.map(id => getVendorById(id)).filter((v): v is VendorEntry => v !== undefined)
}

export function getCategoryById(id: string): VendorCategory | undefined {
  return VENDOR_CATEGORIES.find(c => c.id === id)
}
