// ─────────────────────────────────────────────────────────────────────────────
// preservation/inventory — Wave 6: the machine-readable preservation inventory
// ─────────────────────────────────────────────────────────────────────────────
// The single catalog of everything Waves 1–5 expose that the full-site rebuild MUST
// carry forward unchanged. Generated by reading the current app/route tree, canonical
// metrix engine, storage helpers, cloud schema, analytics, and SEO surfaces as of the
// Wave 6 branch point. Treat this file as an append-only contract: removing an entry is
// a breaking change and the Wave 6 preservation tests will fail if a route, id, key,
// table, or event silently disappears.
//
// Pure data + small pure validators. No runtime side effects, no I/O.
// ─────────────────────────────────────────────────────────────────────────────

import {
  PRESERVATION_INVENTORY_VERSION,
  type PreservationInventory,
  type RouteRecord,
  type CanonicalIdRecord,
  type StorageKeyRecord,
  type CloudTableRecord,
  type AnalyticsEventRecord,
  type SeoSurfaceRecord,
  type ExportDeletionRecord,
} from './inventoryTypes'

// ── Routes ──────────────────────────────────────────────────────────────────────
// Mirrors src/app as of the Wave 6 branch point. Adding routes later is fine; removing
// or renaming any of these without a preserved alias is a breaking change.
export const ROUTE_INVENTORY: RouteRecord[] = [
  { path: '/', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true, notes: 'homepage' },
  { path: '/about', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/start', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/assessment', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/business-readiness', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/results', kind: 'results', shell: 'results', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/report', kind: 'results', shell: 'results', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/dashboard', kind: 'dashboard', shell: 'dashboard', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/foundation-builder', kind: 'dashboard', shell: 'dashboard', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/growth', kind: 'dashboard', shell: 'dashboard', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/resources', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true, notes: 'current resources surface; directory in Wave 7' },
  { path: '/learn', kind: 'content', shell: 'content', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/learn/[slug]', kind: 'content', shell: 'content', dynamicParams: ['slug'], legacyAlias: false, preserve: true },
  { path: '/trades', kind: 'content', shell: 'content', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/platform/[trade]', kind: 'content', shell: 'content', dynamicParams: ['trade'], legacyAlias: false, preserve: true },
  { path: '/platform-ecosystem', kind: 'content', shell: 'content', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/contractor-builders', kind: 'content', shell: 'content', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/general-business-starter', kind: 'content', shell: 'content', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/partners', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/install', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/unlock', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/account/privacy', kind: 'authenticated', shell: 'dashboard', dynamicParams: [], legacyAlias: false, preserve: true },
  // Legal / disclosure
  { path: '/privacy', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/terms', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/disclaimer', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/cancellation', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/affiliate-disclosure', kind: 'public', shell: 'public', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/resource-directory-disclosure', kind: 'public', shell: 'content', dynamicParams: [], legacyAlias: false, preserve: true, notes: 'Wave 7 — full resource directory disclosure' },
  // Spanish discovery
  { path: '/es', kind: 'content', shell: 'content', dynamicParams: [], legacyAlias: false, preserve: true, notes: 'spanish discovery hub' },
  { path: '/es/como-empezar-un-negocio', kind: 'content', shell: 'content', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/es/preparacion-empresarial', kind: 'content', shell: 'content', dynamicParams: [], legacyAlias: false, preserve: true },
  // API routes
  { path: '/api/checkout', kind: 'api', shell: 'none', dynamicParams: [], legacyAlias: false, preserve: true, notes: 'Stripe — UNCHANGED in Wave 6' },
  { path: '/api/webhook', kind: 'api', shell: 'none', dynamicParams: [], legacyAlias: false, preserve: true, notes: 'Stripe — UNCHANGED in Wave 6' },
  { path: '/api/verify-session', kind: 'api', shell: 'none', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/api/track-click', kind: 'api', shell: 'none', dynamicParams: [], legacyAlias: false, preserve: true, notes: 'canonical outbound-click sink (referral_clicks)' },
  { path: '/api/postback/[vendor]', kind: 'api', shell: 'none', dynamicParams: ['vendor'], legacyAlias: false, preserve: true },
  { path: '/api/email-trigger', kind: 'api', shell: 'none', dynamicParams: [], legacyAlias: false, preserve: true },
  // System / SEO
  { path: '/sitemap.xml', kind: 'system', shell: 'none', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/robots.txt', kind: 'system', shell: 'none', dynamicParams: [], legacyAlias: false, preserve: true },
  { path: '/llms.txt', kind: 'system', shell: 'none', dynamicParams: [], legacyAlias: false, preserve: true },
]

// ── Canonical IDs ───────────────────────────────────────────────────────────────
export const CANONICAL_ID_INVENTORY: CanonicalIdRecord[] = [
  { kind: 'profile', pattern: 'mp_<seed>', source: 'src/lib/metrix/snapshot.ts', example: 'mp_hvac_FL', stable: true },
  { kind: 'assessment', pattern: 'szm_assessment_id (uuid)', source: 'src/lib/intake.ts / metrixStorage', example: 'a1b2c3d4', stable: true },
  { kind: 'score', pattern: 'MetrixScore (0–100 derived)', source: 'src/lib/metrix/readModel.ts', example: '72', stable: true, notes: 'projection of canonical readiness; not a stored id' },
  { kind: 'priority', pattern: 'priorityId (domain key)', source: 'src/lib/metrix/metrixPriority.ts', example: 'licensing', stable: true },
  { kind: 'gate', pattern: 'gateId (domain key)', source: 'src/lib/metrix/gates.ts', example: 'gate_licensing', stable: true },
  { kind: 'path', pattern: 'pathId', source: 'src/lib/metrix/completionPaths.ts', example: 'path_licensing_fast', stable: true },
  { kind: 'action', pattern: '<source>:<sourceId>', source: 'src/lib/metrix/actionModel.ts', example: 'metrix_priority:step_1', stable: true, notes: 'source ∈ metrix_priority|foundation|growth' },
  { kind: 'step', pattern: 'stepId (preserved from path)', source: 'src/lib/metrix/completionPaths.ts', example: 'step_register_llc', stable: true },
  { kind: 'question', pattern: 'questionId', source: 'src/lib/questions.ts', example: 'business_type', stable: true },
  { kind: 'trade', pattern: 'CanonicalTradeId', source: 'src/lib/metrix/trades.ts', example: 'hvac', stable: true },
  { kind: 'state', pattern: 'CanonicalStateId (2-letter)', source: 'src/lib/metrix/states.ts', example: 'FL', stable: true },
  { kind: 'resource', pattern: '<source>:<sourceId>', source: 'src/lib/metrix/resourceRegistry.ts', example: 'vendor:jobber', stable: true, notes: 'source ∈ vendor|affiliate|guide' },
  { kind: 'vendor', pattern: 'vendor.id (preserved verbatim)', source: 'src/lib/vendorCategories.ts', example: 'jobber', stable: true },
  { kind: 'referral', pattern: 'referralId', source: 'src/lib/referralEngine.ts', example: 'ref_x', stable: true },
  { kind: 'partner', pattern: 'partner.id', source: 'src/lib/affiliates.ts / partnerDistribution.ts', example: 'next_insurance', stable: true },
  { kind: 'analytics_event', pattern: 'AnalyticsEvent (snake_case)', source: 'src/lib/analytics.ts', example: 'recommendation_impression', stable: true },
  { kind: 'consent_record', pattern: 'consent flag (host-granted)', source: 'src/lib/tracking.ts', example: 'analytics_consent', stable: true },
]

// ── Storage keys ────────────────────────────────────────────────────────────────
export const STORAGE_KEY_INVENTORY: StorageKeyRecord[] = [
  { key: 'szm_metrix_canonical', scope: 'local', owner: 'metrix/persist.ts', cloudTable: null, preserve: true },
  { key: 'szm_metrix_profile', scope: 'local', owner: 'metrixStorage.ts', cloudTable: null, preserve: true },
  { key: 'szm_metrix_history', scope: 'local', owner: 'metrixStorage.ts', cloudTable: 'cloud_sync_score_history', preserve: true },
  { key: 'szm_metrix_last_recorded_at', scope: 'local', owner: 'metrixHistory.ts', cloudTable: null, preserve: true },
  { key: 'szm_priority_progress', scope: 'local', owner: 'metrix/progressStore.ts', cloudTable: 'cloud_sync_priority_progress', preserve: true },
  { key: 'szm_reassessment_history', scope: 'local', owner: 'metrix/reassessmentStore.ts', cloudTable: 'cloud_sync_reassessment_history', preserve: true },
  { key: 'szm_assessment_id', scope: 'local', owner: 'intake.ts', cloudTable: 'cloud_sync_assessment_history', preserve: true },
  { key: 'szm_score', scope: 'local', owner: 'scoring.ts', cloudTable: 'cloud_sync_score_history', preserve: true },
  { key: 'szm_intake', scope: 'local', owner: 'intake.ts', cloudTable: null, preserve: true },
  { key: 'szm_foundation_builder', scope: 'local', owner: 'foundationBuilder.ts', cloudTable: 'cloud_sync_foundation_builder_progress', preserve: true },
  { key: 'szm_foundation_complete', scope: 'local', owner: 'foundationBuilder.ts', cloudTable: 'cloud_sync_foundation_builder_progress', preserve: true },
  { key: 'szm_growth_engine', scope: 'local', owner: 'growthEngine.ts', cloudTable: 'cloud_sync_launch_readiness_progress', preserve: true },
  { key: 'szm_growth_complete', scope: 'local', owner: 'growthEngine.ts', cloudTable: 'cloud_sync_launch_readiness_progress', preserve: true },
  { key: 'szm_growth_events', scope: 'local', owner: 'growthAnalytics.ts', cloudTable: 'cloud_sync_growth_events', preserve: true },
  { key: 'szm_launch_readiness', scope: 'local', owner: 'roadmapProgress.ts', cloudTable: 'cloud_sync_launch_readiness_progress', preserve: true },
  { key: 'szm_path_complete', scope: 'local', owner: 'pathActions.ts', cloudTable: 'cloud_sync_roadmap_action_progress', preserve: true },
  { key: 'szm_feedback', scope: 'local', owner: 'feedback.ts', cloudTable: 'cloud_sync_customer_feedback', preserve: true },
  { key: 'szm_customer_feedback', scope: 'local', owner: 'customerFeedbackSync.ts', cloudTable: 'cloud_sync_customer_feedback', preserve: true },
  { key: 'szm_resource_feedback', scope: 'local', owner: 'metrix/resourceFeedback.ts', cloudTable: null, preserve: true },
  { key: 'szm_vendor_tracker', scope: 'local', owner: 'tracking.ts', cloudTable: 'cloud_sync_vendor_tool_tracker', preserve: true },
  { key: 'szm_partner_interest', scope: 'local', owner: 'partnerInterestSync.ts', cloudTable: 'cloud_sync_partner_interest', preserve: true },
  { key: 'szm_proof_dismissed', scope: 'local', owner: 'customerProof.ts', cloudTable: null, preserve: true },
  { key: 'szm_install_dismissed', scope: 'local', owner: 'InstallPrompt.tsx', cloudTable: null, preserve: true },
]

// ── Cloud tables ─────────────────────────────────────────────────────────────────
export const CLOUD_TABLE_INVENTORY: CloudTableRecord[] = [
  { table: 'cloud_sync_assessment_history', migration: '002', localKey: 'szm_assessment_id', rls: 'owner_only', exportCovered: true, deleteCovered: true },
  { table: 'cloud_sync_score_history', migration: '002', localKey: 'szm_metrix_history', rls: 'owner_only', exportCovered: true, deleteCovered: true },
  { table: 'cloud_sync_roadmap_action_progress', migration: '002', localKey: 'szm_path_complete', rls: 'owner_only', exportCovered: true, deleteCovered: true },
  { table: 'cloud_sync_kpi_entries', migration: '002', localKey: null, rls: 'owner_only', exportCovered: true, deleteCovered: true },
  { table: 'cloud_sync_customer_feedback', migration: '002', localKey: 'szm_customer_feedback', rls: 'owner_only', exportCovered: true, deleteCovered: true },
  { table: 'cloud_sync_partner_interest', migration: '002', localKey: 'szm_partner_interest', rls: 'owner_only', exportCovered: true, deleteCovered: true },
  { table: 'cloud_sync_growth_events', migration: '002', localKey: 'szm_growth_events', rls: 'owner_only', exportCovered: true, deleteCovered: true },
  { table: 'cloud_sync_foundation_builder_progress', migration: '002', localKey: 'szm_foundation_builder', rls: 'owner_only', exportCovered: true, deleteCovered: true },
  { table: 'cloud_sync_vendor_tool_tracker', migration: '002', localKey: 'szm_vendor_tracker', rls: 'owner_only', exportCovered: true, deleteCovered: true },
  { table: 'cloud_sync_launch_readiness_progress', migration: '002', localKey: 'szm_launch_readiness', rls: 'owner_only', exportCovered: true, deleteCovered: true },
  { table: 'cloud_sync_priority_progress', migration: '004', localKey: 'szm_priority_progress', rls: 'owner_only', exportCovered: true, deleteCovered: true },
  { table: 'cloud_sync_reassessment_history', migration: '004', localKey: 'szm_reassessment_history', rls: 'owner_only', exportCovered: true, deleteCovered: true },
]

// ── Analytics events ──────────────────────────────────────────────────────────────
// Mirrors the AnalyticsEvent union in src/lib/analytics.ts exactly. The Wave 6 tests
// assert each is unique; the union itself remains the source of truth for emission.
export const ANALYTICS_EVENT_INVENTORY: AnalyticsEventRecord[] = [
  { name: 'report_view', category: 'report', consentGated: false, carriesPii: false, preserve: true },
  { name: 'feedback_rating_selected', category: 'feedback', consentGated: false, carriesPii: false, preserve: true },
  { name: 'feedback_submitted', category: 'feedback', consentGated: false, carriesPii: false, preserve: true },
  { name: 'resource_shared', category: 'referral', consentGated: false, carriesPii: false, preserve: true },
  { name: 'referral_created', category: 'referral', consentGated: false, carriesPii: false, preserve: true },
  { name: 'share_link_copied', category: 'referral', consentGated: false, carriesPii: false, preserve: true },
  { name: 'feedback_prompt_viewed', category: 'feedback', consentGated: false, carriesPii: false, preserve: true },
  { name: 'feedback_score_selected', category: 'feedback', consentGated: false, carriesPii: false, preserve: true },
  { name: 'testimonial_interest_selected', category: 'feedback', consentGated: false, carriesPii: false, preserve: true },
  { name: 'case_study_interest_selected', category: 'feedback', consentGated: false, carriesPii: false, preserve: true },
  { name: 'product_feedback_submitted', category: 'feedback', consentGated: false, carriesPii: false, preserve: true },
  { name: 'growth_event_tracked', category: 'activation', consentGated: false, carriesPii: false, preserve: true },
  { name: 'acquisition_source_detected', category: 'acquisition', consentGated: false, carriesPii: false, preserve: true },
  { name: 'activation_milestone_reached', category: 'activation', consentGated: false, carriesPii: false, preserve: true },
  { name: 'email_capture_viewed', category: 'acquisition', consentGated: false, carriesPii: false, preserve: true },
  { name: 'email_capture_started', category: 'acquisition', consentGated: false, carriesPii: false, preserve: true },
  { name: 'email_capture_submitted', category: 'acquisition', consentGated: false, carriesPii: false, preserve: true },
  { name: 'email_capture_success', category: 'acquisition', consentGated: false, carriesPii: false, preserve: true },
  { name: 'email_capture_failed', category: 'acquisition', consentGated: false, carriesPii: false, preserve: true },
  { name: 'recommendation_impression', category: 'resource', consentGated: true, carriesPii: false, preserve: true },
  { name: 'recommendation_card_opened', category: 'resource', consentGated: true, carriesPii: false, preserve: true },
  { name: 'recommendation_outbound_click', category: 'resource', consentGated: true, carriesPii: false, preserve: true },
  { name: 'recommendation_feedback_submitted', category: 'resource', consentGated: true, carriesPii: false, preserve: true },
]

// ── SEO surfaces ──────────────────────────────────────────────────────────────────
export const SEO_SURFACE_INVENTORY: SeoSurfaceRecord[] = [
  { kind: 'metadata', source: 'src/lib/seo.ts + per-page metadata', preserve: true },
  { kind: 'open_graph', source: 'src/lib/seo.ts', preserve: true },
  { kind: 'structured_data', source: 'src/lib/seo.ts (JSON-LD)', preserve: true },
  { kind: 'sitemap', source: 'src/app/sitemap.ts', preserve: true },
  { kind: 'robots', source: 'src/app/robots.ts', preserve: true },
  { kind: 'llms_txt', source: 'src/app/llms.txt/route.ts', preserve: true },
  { kind: 'canonical', source: 'src/lib/seo.ts (canonical URLs)', preserve: true },
  { kind: 'spanish_discovery', source: 'src/app/es/* + spanishDiscovery.ts', preserve: true },
  { kind: 'redirect', source: 'next.config.js redirects', preserve: true, notes: 'legacy aliases — preserve all' },
]

// ── Export / deletion ─────────────────────────────────────────────────────────────
export const EXPORT_DELETION_INVENTORY: ExportDeletionRecord[] = [
  { dataset: 'account cloud data (all 12 tables)', exportSource: 'accountDataPrivacy.exportAccountData', deletionSource: 'accountDataPrivacy.deleteAccountData', cloudCovered: true, localCovered: false },
  { dataset: 'device-local synced data', exportSource: 'accountDataPrivacy (per-key)', deletionSource: 'accountDataPrivacy.clearDeviceLocalSyncedData', cloudCovered: false, localCovered: true },
  { dataset: 'foundation builder progress', exportSource: 'foundationBuilder export (CSV/HTML)', deletionSource: 'clearDeviceLocalSyncedData + cloud delete', cloudCovered: true, localCovered: true },
  { dataset: 'action/evidence/outcome', exportSource: 'metrix progress export', deletionSource: 'priority-progress delete', cloudCovered: true, localCovered: true },
  { dataset: 'resource interactions / feedback', exportSource: 'resourceFeedback (device-local)', deletionSource: 'clearResourceFeedback', cloudCovered: false, localCovered: true },
  { dataset: 'reassessment history', exportSource: 'reassessmentStore export', deletionSource: 'reassessment delete', cloudCovered: true, localCovered: true },
]

// ── The assembled inventory ─────────────────────────────────────────────────────────
export const PRESERVATION_INVENTORY: PreservationInventory = {
  version: PRESERVATION_INVENTORY_VERSION,
  routes: ROUTE_INVENTORY,
  canonicalIds: CANONICAL_ID_INVENTORY,
  storageKeys: STORAGE_KEY_INVENTORY,
  cloudTables: CLOUD_TABLE_INVENTORY,
  analyticsEvents: ANALYTICS_EVENT_INVENTORY,
  seoSurfaces: SEO_SURFACE_INVENTORY,
  exportDeletion: EXPORT_DELETION_INVENTORY,
}

// ── Pure validators (used by Wave 6 preservation tests + future CI) ─────────────────
function findDuplicates(values: string[]): string[] {
  const seen = new Set<string>()
  const dupes = new Set<string>()
  for (const v of values) {
    if (seen.has(v)) dupes.add(v)
    seen.add(v)
  }
  return Array.from(dupes)
}

export interface InventoryValidation {
  ok: boolean
  duplicateRoutes: string[]
  duplicateStorageKeys: string[]
  duplicateCloudTables: string[]
  duplicateAnalyticsEvents: string[]
  duplicateCanonicalIdKinds: string[]
  storageKeysWithMissingCloudTable: string[]   // localKey points at an unknown table
  cloudTablesNotExportCovered: string[]
  cloudTablesNotDeleteCovered: string[]
}

/** Structural integrity check over the inventory. Pure; safe to run in tests + CI. */
export function validateInventory(inv: PreservationInventory = PRESERVATION_INVENTORY): InventoryValidation {
  const tableNames = new Set(inv.cloudTables.map(t => t.table))
  const storageKeysWithMissingCloudTable = inv.storageKeys
    .filter(s => s.cloudTable !== null && !tableNames.has(s.cloudTable))
    .map(s => s.key)

  const validation: InventoryValidation = {
    ok: false,
    duplicateRoutes: findDuplicates(inv.routes.map(r => r.path)),
    duplicateStorageKeys: findDuplicates(inv.storageKeys.map(s => s.key)),
    duplicateCloudTables: findDuplicates(inv.cloudTables.map(t => t.table)),
    duplicateAnalyticsEvents: findDuplicates(inv.analyticsEvents.map(e => e.name)),
    duplicateCanonicalIdKinds: findDuplicates(inv.canonicalIds.map(c => c.kind)),
    storageKeysWithMissingCloudTable,
    cloudTablesNotExportCovered: inv.cloudTables.filter(t => !t.exportCovered).map(t => t.table),
    cloudTablesNotDeleteCovered: inv.cloudTables.filter(t => !t.deleteCovered).map(t => t.table),
  }
  validation.ok =
    validation.duplicateRoutes.length === 0 &&
    validation.duplicateStorageKeys.length === 0 &&
    validation.duplicateCloudTables.length === 0 &&
    validation.duplicateAnalyticsEvents.length === 0 &&
    validation.duplicateCanonicalIdKinds.length === 0 &&
    validation.storageKeysWithMissingCloudTable.length === 0 &&
    validation.cloudTablesNotExportCovered.length === 0 &&
    validation.cloudTablesNotDeleteCovered.length === 0
  return validation
}
