// ─────────────────────────────────────────────────────────────────────────────
// metrix/resourceLaunchImport — Wave 7 Checkpoint 5: curated 108 launch-set import map
// ─────────────────────────────────────────────────────────────────────────────
// The deterministic, audited mapping of the curated 108 launch-set records from
// docs/data/SubZeroMetrix_Resource_Directory_Master_Catalog_and_Audit.xlsx (sheet
// "Verified Launch Set") into the canonical Wave 5–6 resource architecture.
//
// IMPORTANT — this is IMPORT/AUDIT METADATA, not published runtime data:
//   - NO record is public-eligible. The workbook's "Verified - official destination identified"
//     means only that a destination was IDENTIFIED; every record's HTTP status is
//     "Not continuously monitored", so the Wave 6 active/healthy-link gate is UNMET.
//   - publicationStatus is 'held_for_review' for ALL 108. public-eligible count = 0.
//   - This module is NOT wired into getPublishedEcosystemCatalog() - the published catalog
//     stays empty. No affiliate/referral/reseller/partner status is inferred here.
//   - The 2,063-item Master Catalog backlog is NOT imported (see MASTER_CATALOG_BACKLOG_SIZE).
//   - Existing canonical IDs always win; workbook IDs are retained only as source references.
//   - Feature flags verified_launch_resources / expanded_resource_catalog /
//     tracked_resource_redirects remain default OFF - nothing is publicly activated.
// ─────────────────────────────────────────────────────────────────────────────

export const RESOURCE_LAUNCH_IMPORT_VERSION = 1

/** Provenance of the curated launch set (the workbook is NOT runtime data; only this map is). */
export const RESOURCE_LAUNCH_IMPORT_SOURCE = {
  workbook: 'docs/data/SubZeroMetrix_Resource_Directory_Master_Catalog_and_Audit.xlsx',
  workbookSha1: 'a1fc6f9c752f718cc06810fe61cd9cb1c84366ce',
  sheet: 'Verified Launch Set',
  table: 'VerifiedLaunchTable',
  curatedRowCount: 108,
  reviewedDate: '2026-06-14',
} as const

/** The full 2,063-item Master Catalog is an UNPUBLISHED backlog - intentionally not imported. */
export const MASTER_CATALOG_BACKLOG_SIZE = 2063
export const MASTER_CATALOG_IMPORTED = false

export type LaunchDisposition =
  | 'reuse_existing' | 'merge_into_existing' | 'create_new' | 'hold_for_review' | 'exclude'

// Truthful internal verification states. 'destination_identified' is the ONLY state any curated
// record has reached; it is NOT 'approved_for_publication'.
export type LaunchVerificationStatus =
  | 'destination_identified' | 'pending_live_link_check' | 'pending_eligibility_review'
  | 'pending_geographic_review' | 'pending_regulated_category_disclosure'
  | 'pending_commercial_status_confirmation' | 'live_link_confirmed' | 'approved_for_publication'
  | 'held' | 'excluded'

export type LaunchPublicationStatus =
  | 'held_for_review' | 'approved_for_publication' | 'public_eligible' | 'excluded'

export interface ResourceLaunchImportRecord {
  workbookResourceId: string
  canonicalResourceId: string | null
  canonicalVendorId: string | null
  providerName: string
  normalizedDomain: string
  resourceType: string
  disposition: LaunchDisposition
  matchReason: string
  matchConfidence: 'high' | 'medium' | 'low'
  verificationStatus: LaunchVerificationStatus
  publicationStatus: LaunchPublicationStatus
  conflictNotes: string
}

export const RESOURCE_LAUNCH_IMPORT: ResourceLaunchImportRecord[] = [
  { workbookResourceId: "VER-001", canonicalResourceId: "vendor:sba-loans", canonicalVendorId: "sba-loans", providerName: "SBA Business Guide", normalizedDomain: "sba.gov", resourceType: "Official/free", disposition: "merge_into_existing", matchReason: "official domain matches existing canonical record; enrich with launch metadata", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-002", canonicalResourceId: null, canonicalVendorId: null, providerName: "IRS Employer Identification Number", normalizedDomain: "irs.gov", resourceType: "Official/free", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-003", canonicalResourceId: null, canonicalVendorId: null, providerName: "OSHA Small Business Resources", normalizedDomain: "osha.gov", resourceType: "Official/free", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-004", canonicalResourceId: null, canonicalVendorId: null, providerName: "SAM.gov Entity Registration", normalizedDomain: "sam.gov", resourceType: "Official/free", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-005", canonicalResourceId: null, canonicalVendorId: null, providerName: "SCORE", normalizedDomain: "score.org", resourceType: "Nonprofit/free", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-006", canonicalResourceId: null, canonicalVendorId: null, providerName: "America’s SBDC", normalizedDomain: "americassbdc.org", resourceType: "Nonprofit/free", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-007", canonicalResourceId: null, canonicalVendorId: null, providerName: "APEX Accelerators", normalizedDomain: "apexaccelerators.us", resourceType: "Government-supported/free", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-008", canonicalResourceId: null, canonicalVendorId: null, providerName: "CISA Small and Midsize Business Resources", normalizedDomain: "cisa.gov", resourceType: "Official/free", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-009", canonicalResourceId: null, canonicalVendorId: null, providerName: "Colorado DORA Division of Professions and Occupations", normalizedDomain: "dpo.colorado.gov", resourceType: "Official/free", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-010", canonicalResourceId: null, canonicalVendorId: null, providerName: "Florida DBPR Construction Industry Licensing Board", normalizedDomain: "www2.myfloridalicense.com", resourceType: "Official/free", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-011", canonicalResourceId: null, canonicalVendorId: null, providerName: "Arizona Registrar of Contractors", normalizedDomain: "roc.az.gov", resourceType: "Official/free", disposition: "merge_into_existing", matchReason: "official domain matches existing canonical record; enrich with launch metadata", matchConfidence: "high", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-012", canonicalResourceId: null, canonicalVendorId: null, providerName: "North Carolina Licensing Board for General Contractors", normalizedDomain: "nclbgc.org", resourceType: "Official/free", disposition: "merge_into_existing", matchReason: "official domain matches existing canonical record; enrich with launch metadata", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-013", canonicalResourceId: null, canonicalVendorId: null, providerName: "Ohio Construction Industry Licensing Board", normalizedDomain: "com.ohio.gov", resourceType: "Official/free", disposition: "merge_into_existing", matchReason: "official domain matches existing canonical record; enrich with launch metadata", matchConfidence: "high", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-014", canonicalResourceId: null, canonicalVendorId: null, providerName: "Texas Department of Licensing and Regulation", normalizedDomain: "tdlr.texas.gov", resourceType: "Official/free", disposition: "merge_into_existing", matchReason: "official domain matches existing canonical record; enrich with launch metadata", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-015", canonicalResourceId: "vendor:legalzoom", canonicalVendorId: "legalzoom", providerName: "LegalZoom", normalizedDomain: "legalzoom.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-016", canonicalResourceId: "vendor:northwest-ra", canonicalVendorId: "northwest-ra", providerName: "Northwest Registered Agent", normalizedDomain: "northwestregisteredagent.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-017", canonicalResourceId: null, canonicalVendorId: null, providerName: "Bizee", normalizedDomain: "bizee.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-018", canonicalResourceId: "vendor:zenbusiness", canonicalVendorId: "zenbusiness", providerName: "ZenBusiness", normalizedDomain: "zenbusiness.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-019", canonicalResourceId: null, canonicalVendorId: null, providerName: "Harbor Compliance", normalizedDomain: "harborcompliance.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-020", canonicalResourceId: null, canonicalVendorId: null, providerName: "Rocket Lawyer", normalizedDomain: "rocketlawyer.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-021", canonicalResourceId: "vendor:chase-business", canonicalVendorId: "chase-business", providerName: "Chase for Business", normalizedDomain: "chase.com", resourceType: "Provider - relationship unverified", disposition: "merge_into_existing", matchReason: "official domain matches existing canonical record; enrich with launch metadata", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-022", canonicalResourceId: null, canonicalVendorId: null, providerName: "Bank of America Business", normalizedDomain: "bankofamerica.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-023", canonicalResourceId: null, canonicalVendorId: null, providerName: "Wells Fargo Small Business", normalizedDomain: "wellsfargo.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-024", canonicalResourceId: null, canonicalVendorId: null, providerName: "U.S. Bank Business", normalizedDomain: "usbank.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-025", canonicalResourceId: null, canonicalVendorId: null, providerName: "PNC Business", normalizedDomain: "pnc.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-026", canonicalResourceId: null, canonicalVendorId: null, providerName: "Truist Small Business", normalizedDomain: "truist.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-027", canonicalResourceId: "vendor:capital-one-spark", canonicalVendorId: "capital-one-spark", providerName: "Capital One Business", normalizedDomain: "capitalone.com", resourceType: "Provider - relationship unverified", disposition: "merge_into_existing", matchReason: "official domain matches existing canonical record; enrich with launch metadata", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-028", canonicalResourceId: null, canonicalVendorId: null, providerName: "TD Small Business", normalizedDomain: "td.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-029", canonicalResourceId: null, canonicalVendorId: null, providerName: "Found", normalizedDomain: "found.com", resourceType: "Public partner/affiliate path reported; terms must be verified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-030", canonicalResourceId: "vendor:relay", canonicalVendorId: "relay", providerName: "Relay", normalizedDomain: "relayfi.com", resourceType: "Partner path; eligibility must be verified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-031", canonicalResourceId: "vendor:bluevine", canonicalVendorId: "bluevine", providerName: "Bluevine", normalizedDomain: "bluevine.com", resourceType: "Provider - relationship unverified", disposition: "merge_into_existing", matchReason: "official domain matches existing canonical record; enrich with launch metadata", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-032", canonicalResourceId: null, canonicalVendorId: null, providerName: "Novo", normalizedDomain: "novo.co", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-033", canonicalResourceId: "vendor:mercury", canonicalVendorId: "mercury", providerName: "Mercury", normalizedDomain: "mercury.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-034", canonicalResourceId: null, canonicalVendorId: null, providerName: "Live Oak Bank", normalizedDomain: "liveoak.bank", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-035", canonicalResourceId: "vendor:the-hartford", canonicalVendorId: "the-hartford", providerName: "The Hartford", normalizedDomain: "thehartford.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-036", canonicalResourceId: null, canonicalVendorId: null, providerName: "Travelers", normalizedDomain: "travelers.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-037", canonicalResourceId: null, canonicalVendorId: null, providerName: "Liberty Mutual Business Insurance", normalizedDomain: "business.libertymutual.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-038", canonicalResourceId: null, canonicalVendorId: null, providerName: "Nationwide Business Insurance", normalizedDomain: "nationwide.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-039", canonicalResourceId: null, canonicalVendorId: null, providerName: "Progressive Commercial", normalizedDomain: "progressivecommercial.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-040", canonicalResourceId: null, canonicalVendorId: null, providerName: "State Farm Small Business Insurance", normalizedDomain: "statefarm.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-041", canonicalResourceId: null, canonicalVendorId: null, providerName: "Chubb Small Business", normalizedDomain: "chubb.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-042", canonicalResourceId: null, canonicalVendorId: null, providerName: "CNA", normalizedDomain: "cna.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-043", canonicalResourceId: null, canonicalVendorId: null, providerName: "Zurich North America", normalizedDomain: "zurichna.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-044", canonicalResourceId: "vendor:next-insurance", canonicalVendorId: "next-insurance", providerName: "ERGO NEXT", normalizedDomain: "nextinsurance.com", resourceType: "Public affiliate/embedded paths reported; terms must be verified", disposition: "merge_into_existing", matchReason: "official domain matches existing canonical record; enrich with launch metadata", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-045", canonicalResourceId: "vendor:simply-business", canonicalVendorId: "simply-business", providerName: "Simply Business", normalizedDomain: "simplybusiness.com", resourceType: "Strategic partnership path reported; terms must be verified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-046", canonicalResourceId: null, canonicalVendorId: null, providerName: "Thimble", normalizedDomain: "thimble.com", resourceType: "Public affiliate path reported; terms must be verified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-047", canonicalResourceId: null, canonicalVendorId: null, providerName: "Pie Insurance", normalizedDomain: "pieinsurance.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-048", canonicalResourceId: "vendor:hiscox", canonicalVendorId: "hiscox", providerName: "Hiscox", normalizedDomain: "hiscox.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-049", canonicalResourceId: "vendor:biberk", canonicalVendorId: "biberk", providerName: "biBerk", normalizedDomain: "biberk.com", resourceType: "Provider - relationship unverified", disposition: "merge_into_existing", matchReason: "official domain matches existing canonical record; enrich with launch metadata", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-050", canonicalResourceId: null, canonicalVendorId: null, providerName: "Insureon", normalizedDomain: "insureon.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-051", canonicalResourceId: null, canonicalVendorId: null, providerName: "SuretyBonds.com", normalizedDomain: "suretybonds.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-052", canonicalResourceId: "vendor:servicetitan", canonicalVendorId: "servicetitan", providerName: "ServiceTitan", normalizedDomain: "servicetitan.com", resourceType: "Direct partnership path; terms unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-053", canonicalResourceId: "vendor:housecall-pro", canonicalVendorId: "housecall-pro", providerName: "Housecall Pro", normalizedDomain: "housecallpro.com", resourceType: "Public affiliate/referral paths reported; terms must be verified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-054", canonicalResourceId: "vendor:jobber", canonicalVendorId: "jobber", providerName: "Jobber", normalizedDomain: "getjobber.com", resourceType: "Provider - partnership status unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-055", canonicalResourceId: "vendor:fieldedge", canonicalVendorId: "fieldedge", providerName: "FieldEdge", normalizedDomain: "fieldedge.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-056", canonicalResourceId: "vendor:workiz", canonicalVendorId: "workiz", providerName: "Workiz", normalizedDomain: "workiz.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-057", canonicalResourceId: "vendor:service-fusion", canonicalVendorId: "service-fusion", providerName: "Service Fusion", normalizedDomain: "servicefusion.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-058", canonicalResourceId: "vendor:fieldpulse", canonicalVendorId: "fieldpulse", providerName: "FieldPulse", normalizedDomain: "fieldpulse.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-059", canonicalResourceId: "vendor:buildops", canonicalVendorId: "buildops", providerName: "BuildOps", normalizedDomain: "buildops.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-060", canonicalResourceId: "vendor:simprogroup", canonicalVendorId: "simprogroup", providerName: "Simpro", normalizedDomain: "simprogroup.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-061", canonicalResourceId: "vendor:profit-rhino", canonicalVendorId: "profit-rhino", providerName: "Profit Rhino", normalizedDomain: "profitrhino.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-062", canonicalResourceId: null, canonicalVendorId: null, providerName: "The New Flat Rate", normalizedDomain: "thenewflatrate.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-063", canonicalResourceId: null, canonicalVendorId: null, providerName: "Coolfront", normalizedDomain: "coolfront.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-064", canonicalResourceId: null, canonicalVendorId: null, providerName: "STACK", normalizedDomain: "stackct.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-065", canonicalResourceId: null, canonicalVendorId: null, providerName: "Bluebeam", normalizedDomain: "bluebeam.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-066", canonicalResourceId: null, canonicalVendorId: null, providerName: "RSMeans Data", normalizedDomain: "rsmeans.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-067", canonicalResourceId: null, canonicalVendorId: null, providerName: "Johnstone Supply", normalizedDomain: "johnstonesupply.com", resourceType: "Supplier - local account requirements", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-068", canonicalResourceId: null, canonicalVendorId: null, providerName: "R.E. Michel Company", normalizedDomain: "remichel.com", resourceType: "Supplier - regional availability", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-069", canonicalResourceId: null, canonicalVendorId: null, providerName: "United Refrigeration", normalizedDomain: "uri.com", resourceType: "Supplier - branch availability", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-070", canonicalResourceId: null, canonicalVendorId: null, providerName: "Ferguson", normalizedDomain: "ferguson.com", resourceType: "Supplier - trade account options", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-071", canonicalResourceId: null, canonicalVendorId: null, providerName: "Winsupply", normalizedDomain: "winsupplyinc.com", resourceType: "Supplier - local availability", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-072", canonicalResourceId: null, canonicalVendorId: null, providerName: "Hajoca", normalizedDomain: "hajoca.com", resourceType: "Supplier - local brand availability", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-073", canonicalResourceId: null, canonicalVendorId: null, providerName: "Graybar", normalizedDomain: "graybar.com", resourceType: "Supplier - account requirements", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-074", canonicalResourceId: null, canonicalVendorId: null, providerName: "Wesco", normalizedDomain: "wesco.com", resourceType: "Supplier - account requirements", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-075", canonicalResourceId: null, canonicalVendorId: null, providerName: "Sonepar USA", normalizedDomain: "soneparusa.com", resourceType: "Supplier network - local brand availability", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-076", canonicalResourceId: null, canonicalVendorId: null, providerName: "CED", normalizedDomain: "cedcareers.com", resourceType: "Supplier - verify local operating company", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-077", canonicalResourceId: null, canonicalVendorId: null, providerName: "City Electric Supply", normalizedDomain: "cityelectricsupply.com", resourceType: "Supplier - branch availability", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-078", canonicalResourceId: null, canonicalVendorId: null, providerName: "ABC Supply", normalizedDomain: "abcsupply.com", resourceType: "Supplier - trade account requirements", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-079", canonicalResourceId: null, canonicalVendorId: null, providerName: "SRS Distribution", normalizedDomain: "srsdistribution.com", resourceType: "Supplier - local brand availability", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-080", canonicalResourceId: null, canonicalVendorId: null, providerName: "Builders FirstSource", normalizedDomain: "bldr.com", resourceType: "Supplier - regional product availability", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-081", canonicalResourceId: null, canonicalVendorId: null, providerName: "White Cap", normalizedDomain: "whitecap.com", resourceType: "Supplier - branch availability", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-082", canonicalResourceId: null, canonicalVendorId: null, providerName: "Grainger", normalizedDomain: "grainger.com", resourceType: "Supplier - business account options", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-083", canonicalResourceId: null, canonicalVendorId: null, providerName: "Fastenal", normalizedDomain: "fastenal.com", resourceType: "Supplier - branch availability", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-084", canonicalResourceId: null, canonicalVendorId: null, providerName: "SupplyHouse", normalizedDomain: "supplyhouse.com", resourceType: "Supplier - online availability", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_geographic_review" },
  { workbookResourceId: "VER-085", canonicalResourceId: "vendor:quickbooks", canonicalVendorId: "quickbooks", providerName: "QuickBooks Online", normalizedDomain: "quickbooks.intuit.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-086", canonicalResourceId: "vendor:xero", canonicalVendorId: "xero", providerName: "Xero", normalizedDomain: "xero.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-087", canonicalResourceId: "vendor:gusto", canonicalVendorId: "gusto", providerName: "Gusto", normalizedDomain: "gusto.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-088", canonicalResourceId: "vendor:adp", canonicalVendorId: "adp", providerName: "ADP", normalizedDomain: "adp.com", resourceType: "Provider - relationship unverified", disposition: "merge_into_existing", matchReason: "official domain matches existing canonical record; enrich with launch metadata", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-089", canonicalResourceId: "vendor:paychex", canonicalVendorId: "paychex", providerName: "Paychex", normalizedDomain: "paychex.com", resourceType: "Provider - relationship unverified", disposition: "merge_into_existing", matchReason: "official domain matches existing canonical record; enrich with launch metadata", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation; pending_regulated_category_disclosure" },
  { workbookResourceId: "VER-090", canonicalResourceId: "vendor:clockshark", canonicalVendorId: "clockshark", providerName: "ClockShark", normalizedDomain: "clockshark.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-091", canonicalResourceId: null, canonicalVendorId: null, providerName: "busybusy", normalizedDomain: "busybusy.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-092", canonicalResourceId: null, canonicalVendorId: null, providerName: "BILL", normalizedDomain: "bill.com", resourceType: "Provider - relationship unverified", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-093", canonicalResourceId: null, canonicalVendorId: null, providerName: "Google Business Profile", normalizedDomain: "google.com", resourceType: "Official/free core product", disposition: "hold_for_review", matchReason: "provider name matches existing record but official domain differs; confirm same provider before merge", matchConfidence: "low", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "name matches existing record but domain differs; pending_live_link_check" },
  { workbookResourceId: "VER-094", canonicalResourceId: "vendor:constant-contact", canonicalVendorId: "constant-contact", providerName: "Constant Contact", normalizedDomain: "constantcontact.com", resourceType: "Public affiliate/partner paths reported; terms must be verified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-095", canonicalResourceId: "vendor:mailchimp", canonicalVendorId: "mailchimp", providerName: "Mailchimp", normalizedDomain: "mailchimp.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-096", canonicalResourceId: "vendor:podium", canonicalVendorId: "podium", providerName: "Podium", normalizedDomain: "podium.com", resourceType: "Referral/partner paths reported; terms must be verified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-097", canonicalResourceId: "vendor:birdeye", canonicalVendorId: "birdeye", providerName: "Birdeye", normalizedDomain: "birdeye.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-098", canonicalResourceId: "vendor:nicejob", canonicalVendorId: "nicejob", providerName: "NiceJob", normalizedDomain: "nicejob.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-099", canonicalResourceId: "vendor:callrail", canonicalVendorId: "callrail", providerName: "CallRail", normalizedDomain: "callrail.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-100", canonicalResourceId: "vendor:openphone", canonicalVendorId: "openphone", providerName: "OpenPhone", normalizedDomain: "openphone.com", resourceType: "Provider - relationship unverified", disposition: "reuse_existing", matchReason: "domain+name match existing canonical record", matchConfidence: "high", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-101", canonicalResourceId: null, canonicalVendorId: null, providerName: "ACCA", normalizedDomain: "acca.org", resourceType: "Association/member resource", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-102", canonicalResourceId: null, canonicalVendorId: null, providerName: "NATE", normalizedDomain: "natex.org", resourceType: "Certification body", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-103", canonicalResourceId: null, canonicalVendorId: null, providerName: "ESCO Institute", normalizedDomain: "escogroup.org", resourceType: "Certification/training provider", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "destination_identified", publicationStatus: "held_for_review", conflictNotes: "pending_live_link_check; pending_commercial_status_confirmation" },
  { workbookResourceId: "VER-104", canonicalResourceId: null, canonicalVendorId: null, providerName: "NFPA", normalizedDomain: "nfpa.org", resourceType: "Nonprofit standards organization", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-105", canonicalResourceId: null, canonicalVendorId: null, providerName: "Independent Electrical Contractors", normalizedDomain: "ieci.org", resourceType: "Association/member resource", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-106", canonicalResourceId: null, canonicalVendorId: null, providerName: "PHCC", normalizedDomain: "phccweb.org", resourceType: "Association/member resource", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-107", canonicalResourceId: null, canonicalVendorId: null, providerName: "IAPMO", normalizedDomain: "iapmo.org", resourceType: "Standards/certification organization", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check" },
  { workbookResourceId: "VER-108", canonicalResourceId: null, canonicalVendorId: null, providerName: "NCCER", normalizedDomain: "nccer.org", resourceType: "Nonprofit education foundation", disposition: "create_new", matchReason: "no domain/name match in canonical sources", matchConfidence: "medium", verificationStatus: "live_link_confirmed", publicationStatus: "approved_for_publication", conflictNotes: "pending_live_link_check" },
]

/** Deterministic summary of the import (used by the audit doc + tests). */
export function summarizeLaunchImport(map: ResourceLaunchImportRecord[] = RESOURCE_LAUNCH_IMPORT) {
  const by = (k: (r: ResourceLaunchImportRecord) => string) =>
    map.reduce<Record<string, number>>((a, r) => { const v = k(r); a[v] = (a[v] ?? 0) + 1; return a }, {})
  return {
    total: map.length,
    dispositions: by(r => r.disposition),
    publicationStatuses: by(r => r.publicationStatus),
    verificationStatuses: by(r => r.verificationStatus),
    approvedForPublication: map.filter(r => r.publicationStatus === 'approved_for_publication').length,
    publicEligible: map.filter(r => r.publicationStatus === 'public_eligible' || r.publicationStatus === 'approved_for_publication').length,
    pendingVerification: map.filter(r => r.publicationStatus === 'held_for_review').length,
    resolvedCanonicalIds: map.filter(r => r.canonicalResourceId).length,
  }
}
