// ─────────────────────────────────────────────────────────────────────────────
// metrix/resourceLinkAudit — Wave 7 Build-A: liveness evidence for the curated 108
// ─────────────────────────────────────────────────────────────────────────────
// Machine-readable results of the automated liveness test of every curated launch URL
// (sheet "Verified Launch Set"). Read-only HTTP liveness only: no auth/CAPTCHA bypass, no page
// bodies retained (only <title>), no cookies/auth headers logged, bounded concurrency + timeouts.
//
// IMPORTANT — this is VERIFICATION EVIDENCE, not an activation:
//   - ACTIVATION IS HELD at the legal/compliance + architectural gate. ACTIVATED_COUNT = 0.
//   - This module is NOT wired into getPublishedEcosystemCatalog() — the published catalog stays
//     EMPTY. No record's publicationStatus/verificationStatus in the CP5 import map was flipped.
//   - "healthy" here is a TECHNICAL result only; it is not endorsement, preferment, or full
//     verification, and it does not by itself authorize publication.
// ─────────────────────────────────────────────────────────────────────────────

export const RESOURCE_LINK_AUDIT_VERSION = 1

export const RESOURCE_LINK_AUDIT_SOURCE = {
  workbook: 'docs/data/SubZeroMetrix_Resource_Directory_Master_Catalog_and_Audit.xlsx',
  sheet: 'Verified Launch Set',
  testedCount: 108,
  method: 'read-only HTTP liveness (HEAD/GET, manual redirect follow, title only)',
  activationHeld: true,
} as const

/** Activation status. Build A held activation at the legal gate; the owner subsequently approved
 * publication with the educational-directory disclosure framework, activating the 88 technically-
 * verified records (the 20 blocked/failed/mismatch records stay held). */
export const ACTIVATION_HELD = false
export const ACTIVATED_COUNT = 88
export const HELD_COUNT = 20

export type LinkClassification =
  | 'healthy' | 'healthy_with_redirect' | 'temporary_failure' | 'permanent_failure'
  | 'blocked_or_rate_limited' | 'authentication_required' | 'domain_mismatch'
  | 'unexpected_content' | 'manual_review_required'

export interface ResourceLinkResult {
  workbookResourceId: string
  canonicalResourceId: string | null
  providerName: string
  resourceType: string
  originalUrl: string
  finalUrl: string
  normalizedDomain: string
  finalDomain: string
  httpStatus: number
  redirectCount: number
  https: boolean
  responseMs: number | null
  contentType: string | null
  pageTitle: string | null
  testedAt: string
  classification: LinkClassification
  failureReason: string | null
  manualReviewRequired: boolean
}

export const RESOURCE_LINK_AUDIT: ResourceLinkResult[] = [
  { workbookResourceId: "VER-001", canonicalResourceId: "vendor:sba-loans", providerName: "SBA Business Guide", resourceType: "Official/free", originalUrl: "https://www.sba.gov/business-guide", finalUrl: "https://www.sba.gov/business-guide", normalizedDomain: "sba.gov", finalDomain: "sba.gov", httpStatus: 200, redirectCount: 0, https: true, responseMs: 1665, contentType: "text/html; charset=UTF-8", pageTitle: "Business Guide | U.S. Small Business Administration", testedAt: "2026-06-14T14:57:37.857Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-002", canonicalResourceId: null, providerName: "IRS Employer Identification Number", resourceType: "Official/free", originalUrl: "https://www.irs.gov/businesses/employer-identification-number", finalUrl: "https://www.irs.gov/businesses/employer-identification-number", normalizedDomain: "irs.gov", finalDomain: "irs.gov", httpStatus: 200, redirectCount: 0, https: true, responseMs: 404, contentType: "text/html; charset=UTF-8", pageTitle: "Employer identification number | Internal Revenue Service", testedAt: "2026-06-14T14:57:36.850Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-003", canonicalResourceId: null, providerName: "OSHA Small Business Resources", resourceType: "Official/free", originalUrl: "https://www.osha.gov/smallbusiness", finalUrl: "https://www.osha.gov/smallbusiness", normalizedDomain: "osha.gov", finalDomain: "osha.gov", httpStatus: 403, redirectCount: 0, https: true, responseMs: 110, contentType: "text/html", pageTitle: null, testedAt: "2026-06-14T14:57:36.754Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-004", canonicalResourceId: null, providerName: "SAM.gov Entity Registration", resourceType: "Official/free", originalUrl: "https://sam.gov/entity-registration", finalUrl: "https://sam.gov/entity-registration", normalizedDomain: "sam.gov", finalDomain: "sam.gov", httpStatus: 200, redirectCount: 0, https: true, responseMs: 840, contentType: "text/html; charset=UTF-8", pageTitle: "Entity Registration | SAM.gov", testedAt: "2026-06-14T14:57:37.636Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-005", canonicalResourceId: null, providerName: "SCORE", resourceType: "Nonprofit/free", originalUrl: "https://www.score.org/", finalUrl: "https://www.score.org/", normalizedDomain: "score.org", finalDomain: "score.org", httpStatus: 403, redirectCount: 0, https: true, responseMs: 122, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:36.867Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-006", canonicalResourceId: null, providerName: "America’s SBDC", resourceType: "Nonprofit/free", originalUrl: "https://americassbdc.org/", finalUrl: "https://americassbdc.org/", normalizedDomain: "americassbdc.org", finalDomain: "americassbdc.org", httpStatus: 200, redirectCount: 0, https: true, responseMs: 2841, contentType: "text/html; charset=UTF-8", pageTitle: "Home - America's SBDC", testedAt: "2026-06-14T14:57:39.192Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-007", canonicalResourceId: null, providerName: "APEX Accelerators", resourceType: "Government-supported/free", originalUrl: "https://www.apexaccelerators.us/", finalUrl: "https://www.apexaccelerators.us/", normalizedDomain: "apexaccelerators.us", finalDomain: "apexaccelerators.us", httpStatus: 200, redirectCount: 0, https: true, responseMs: 731, contentType: "text/html; charset=UTF-8", pageTitle: "APEX Accelerators", testedAt: "2026-06-14T14:57:38.111Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-008", canonicalResourceId: null, providerName: "CISA Small and Midsize Business Resources", resourceType: "Official/free", originalUrl: "https://www.cisa.gov/resources-tools/resources/small-and-midsize-businesses", finalUrl: "https://www.cisa.gov/resources-tools/resources/small-and-midsize-businesses", normalizedDomain: "cisa.gov", finalDomain: "cisa.gov", httpStatus: 404, redirectCount: 0, https: true, responseMs: 415, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:37.266Z", classification: "permanent_failure", failureReason: "http_404", manualReviewRequired: false },
  { workbookResourceId: "VER-009", canonicalResourceId: null, providerName: "Colorado DORA Division of Professions and Occupations", resourceType: "Official/free", originalUrl: "https://dpo.colorado.gov/", finalUrl: "https://dpo.colorado.gov/", normalizedDomain: "dpo.colorado.gov", finalDomain: "dpo.colorado.gov", httpStatus: 403, redirectCount: 0, https: true, responseMs: 61, contentType: "text/html", pageTitle: null, testedAt: "2026-06-14T14:57:37.151Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-010", canonicalResourceId: null, providerName: "Florida DBPR Construction Industry Licensing Board", resourceType: "Official/free", originalUrl: "https://www2.myfloridalicense.com/construction-industry/", finalUrl: "https://www2.myfloridalicense.com/construction-industry/", normalizedDomain: "www2.myfloridalicense.com", finalDomain: "www2.myfloridalicense.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 144, contentType: "text/html; charset=UTF-8", pageTitle: "Construction Industry &#8211; MyFloridaLicense.com", testedAt: "2026-06-14T14:57:37.491Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-011", canonicalResourceId: null, providerName: "Arizona Registrar of Contractors", resourceType: "Official/free", originalUrl: "https://roc.az.gov/", finalUrl: "https://roc.az.gov/", normalizedDomain: "roc.az.gov", finalDomain: "roc.az.gov", httpStatus: 403, redirectCount: 0, https: true, responseMs: 183, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:37.684Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-012", canonicalResourceId: null, providerName: "North Carolina Licensing Board for General Contractors", resourceType: "Official/free", originalUrl: "https://www.nclbgc.org/", finalUrl: "https://www.nclbgc.org/", normalizedDomain: "nclbgc.org", finalDomain: "nclbgc.org", httpStatus: 200, redirectCount: 0, https: true, responseMs: 247, contentType: "text/html; charset=UTF-8", pageTitle: "NC Licensing Board for General Contractors", testedAt: "2026-06-14T14:57:37.874Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-013", canonicalResourceId: null, providerName: "Ohio Construction Industry Licensing Board", resourceType: "Official/free", originalUrl: "https://com.ohio.gov/divisions-and-programs/industrial-compliance/boards/ohio-construction-industry-licensing-board", finalUrl: "https://com.ohio.gov/divisions-and-programs/industrial-compliance/boards/ohio-construction-industry-licensing-board", normalizedDomain: "com.ohio.gov", finalDomain: "com.ohio.gov", httpStatus: 404, redirectCount: 0, https: true, responseMs: 392, contentType: "text/html", pageTitle: null, testedAt: "2026-06-14T14:57:38.028Z", classification: "permanent_failure", failureReason: "http_404", manualReviewRequired: false },
  { workbookResourceId: "VER-014", canonicalResourceId: null, providerName: "Texas Department of Licensing and Regulation", resourceType: "Official/free", originalUrl: "https://www.tdlr.texas.gov/", finalUrl: "https://www.tdlr.texas.gov/", normalizedDomain: "tdlr.texas.gov", finalDomain: "tdlr.texas.gov", httpStatus: 200, redirectCount: 0, https: true, responseMs: 265, contentType: "text/html", pageTitle: "Texas Department of Licensing and Regulation - Texas.gov", testedAt: "2026-06-14T14:57:38.152Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-015", canonicalResourceId: "vendor:legalzoom", providerName: "LegalZoom", resourceType: "Provider - relationship unverified", originalUrl: "https://www.legalzoom.com/", finalUrl: "https://www.legalzoom.com/", normalizedDomain: "legalzoom.com", finalDomain: "legalzoom.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 462, contentType: "text/html", pageTitle: "LegalZoom | Legal Solutions Trusted By Millions, Designed for You", testedAt: "2026-06-14T14:57:38.630Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-016", canonicalResourceId: "vendor:northwest-ra", providerName: "Northwest Registered Agent", resourceType: "Provider - relationship unverified", originalUrl: "https://www.northwestregisteredagent.com/", finalUrl: "https://www.northwestregisteredagent.com/", normalizedDomain: "northwestregisteredagent.com", finalDomain: "northwestregisteredagent.com", httpStatus: 403, redirectCount: 0, https: true, responseMs: 83, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:38.093Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-017", canonicalResourceId: null, providerName: "Bizee", resourceType: "Provider - relationship unverified", originalUrl: "https://bizee.com/", finalUrl: "https://bizee.com/", normalizedDomain: "bizee.com", finalDomain: "bizee.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 283, contentType: "text/html; charset=utf-8", pageTitle: "Bizee® | LLC Filing & Business Formation | Start a Company", testedAt: "2026-06-14T14:57:38.439Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-018", canonicalResourceId: "vendor:zenbusiness", providerName: "ZenBusiness", resourceType: "Provider - relationship unverified", originalUrl: "https://www.zenbusiness.com/", finalUrl: "https://www.zenbusiness.com/", normalizedDomain: "zenbusiness.com", finalDomain: "zenbusiness.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 143, contentType: "text/html; charset=UTF-8", pageTitle: "Start &amp; Grow Your Business with the ZenBusiness Platform", testedAt: "2026-06-14T14:57:38.332Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-019", canonicalResourceId: null, providerName: "Harbor Compliance", resourceType: "Provider - relationship unverified", originalUrl: "https://www.harborcompliance.com/", finalUrl: "https://www.harborcompliance.com/", normalizedDomain: "harborcompliance.com", finalDomain: "harborcompliance.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 482, contentType: "text/html; charset=UTF-8", pageTitle: "State Licensing Compliance Platform | Harbor Compliance", testedAt: "2026-06-14T14:57:38.994Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-020", canonicalResourceId: null, providerName: "Rocket Lawyer", resourceType: "Provider - relationship unverified", originalUrl: "https://www.rocketlawyer.com/", finalUrl: "https://www.rocketlawyer.com/", normalizedDomain: "rocketlawyer.com", finalDomain: "rocketlawyer.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 408, contentType: "text/html; charset=utf-8", pageTitle: "Rocket Lawyer: AI Legal Help, Contracts, Business Services &amp; Human Legal Pros | Rocket Lawyer", testedAt: "2026-06-14T14:57:38.871Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-021", canonicalResourceId: "vendor:chase-business", providerName: "Chase for Business", resourceType: "Provider - relationship unverified", originalUrl: "https://www.chase.com/business", finalUrl: "https://www.chase.com/business", normalizedDomain: "chase.com", finalDomain: "chase.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 177, contentType: "text/html; charset=utf-8", pageTitle: "Business Banking: Checking, Saving &amp; Loans | Chase for Business | Chase.com", testedAt: "2026-06-14T14:57:39.175Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-022", canonicalResourceId: null, providerName: "Bank of America Business", resourceType: "Provider - relationship unverified", originalUrl: "https://www.bankofamerica.com/smallbusiness/", finalUrl: "https://www.bankofamerica.com/business/", normalizedDomain: "bankofamerica.com", finalDomain: "bankofamerica.com", httpStatus: 200, redirectCount: 1, https: true, responseMs: 169, contentType: "text/html", pageTitle: "Business Banking, Credit Cards &amp; Loans - Bank of America", testedAt: "2026-06-14T14:57:39.055Z", classification: "healthy_with_redirect", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-023", canonicalResourceId: null, providerName: "Wells Fargo Small Business", resourceType: "Provider - relationship unverified", originalUrl: "https://www.wellsfargo.com/biz/", finalUrl: "https://www.wellsfargo.com/biz/", normalizedDomain: "wellsfargo.com", finalDomain: "wellsfargo.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 285, contentType: "text/html;charset=UTF-8", pageTitle: "Business Banking | Wells Fargo", testedAt: "2026-06-14T14:57:39.251Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-024", canonicalResourceId: null, providerName: "U.S. Bank Business", resourceType: "Provider - relationship unverified", originalUrl: "https://www.usbank.com/business-banking.html", finalUrl: "https://www.usbank.com/business-banking.html", normalizedDomain: "usbank.com", finalDomain: "usbank.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 247, contentType: "text/html;charset=utf-8", pageTitle: "Small Business Banking | U.S. Bank", testedAt: "2026-06-14T14:57:39.320Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-025", canonicalResourceId: null, providerName: "PNC Business", resourceType: "Provider - relationship unverified", originalUrl: "https://www.pnc.com/en/small-business.html", finalUrl: "https://www.pnc.com/en/small-business.html", normalizedDomain: "pnc.com", finalDomain: "pnc.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 254, contentType: "text/html;charset=utf-8", pageTitle: "Small Business Banking | PNC Bank", testedAt: "2026-06-14T14:57:39.506Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-026", canonicalResourceId: null, providerName: "Truist Small Business", resourceType: "Provider - relationship unverified", originalUrl: "https://www.truist.com/small-business", finalUrl: "https://www.truist.com/small-business", normalizedDomain: "truist.com", finalDomain: "truist.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 188, contentType: "text/html;charset=utf-8", pageTitle: "Small Business Bank Accounts, Loans &amp; Credit Cards | Truist", testedAt: "2026-06-14T14:57:39.309Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-027", canonicalResourceId: "vendor:capital-one-spark", providerName: "Capital One Business", resourceType: "Provider - relationship unverified", originalUrl: "https://www.capitalone.com/small-business/", finalUrl: "https://www.capitalone.com/small-business/homepage/", normalizedDomain: "capitalone.com", finalDomain: "capitalone.com", httpStatus: 200, redirectCount: 1, https: true, responseMs: 197, contentType: "text/html", pageTitle: "Small Business Financial Solutions", testedAt: "2026-06-14T14:57:39.695Z", classification: "healthy_with_redirect", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-028", canonicalResourceId: null, providerName: "TD Small Business", resourceType: "Provider - relationship unverified", originalUrl: "https://www.td.com/us/en/small-business", finalUrl: "https://www.td.com/us/en/small-business", normalizedDomain: "td.com", finalDomain: "td.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 486, contentType: "text/html;charset=utf-8", pageTitle: "Small Business Banking: Services, Lending &amp; Resources | TD Bank", testedAt: "2026-06-14T14:57:39.844Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-029", canonicalResourceId: null, providerName: "Found", resourceType: "Public partner/affiliate path reported; terms must be verified", originalUrl: "https://found.com/", finalUrl: "https://found.com/", normalizedDomain: "found.com", finalDomain: "found.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 1069, contentType: "text/html; charset=utf-8", pageTitle: "Found | Online Business Checking for Small Business Owners", testedAt: "2026-06-14T14:57:41.678Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-030", canonicalResourceId: "vendor:relay", providerName: "Relay", resourceType: "Partner path; eligibility must be verified", originalUrl: "https://relayfi.com/", finalUrl: "https://relayfi.com/", normalizedDomain: "relayfi.com", finalDomain: "relayfi.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 178, contentType: "text/html; charset=utf-8", pageTitle: "Relay | Online Business Banking | On The Money, All The Time", testedAt: "2026-06-14T14:57:39.560Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-031", canonicalResourceId: "vendor:bluevine", providerName: "Bluevine", resourceType: "Provider - relationship unverified", originalUrl: "https://www.bluevine.com/", finalUrl: "https://www.bluevine.com/", normalizedDomain: "bluevine.com", finalDomain: "bluevine.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 282, contentType: "text/html; charset=utf-8", pageTitle: "Online Business Banking Solutions &amp; Services | Bluevine", testedAt: "2026-06-14T14:57:39.766Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-032", canonicalResourceId: null, providerName: "Novo", resourceType: "Provider - relationship unverified", originalUrl: "https://www.novo.co/", finalUrl: "https://www.novo.co/", normalizedDomain: "novo.co", finalDomain: "novo.co", httpStatus: 200, redirectCount: 0, https: true, responseMs: 228, contentType: "text/html", pageTitle: "Online Business Banking Solutions | Novo", testedAt: "2026-06-14T14:57:39.848Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-033", canonicalResourceId: "vendor:mercury", providerName: "Mercury", resourceType: "Provider - relationship unverified", originalUrl: "https://mercury.com/", finalUrl: "https://mercury.com/", normalizedDomain: "mercury.com", finalDomain: "mercury.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 242, contentType: "text/html; charset=utf-8", pageTitle: "Online Business Banking For Startups, Small Businesses &amp; Scaling Companies", testedAt: "2026-06-14T14:57:40.007Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-034", canonicalResourceId: null, providerName: "Live Oak Bank", resourceType: "Provider - relationship unverified", originalUrl: "https://www.liveoak.bank/", finalUrl: "https://www.liveoak.bank/", normalizedDomain: "liveoak.bank", finalDomain: "liveoak.bank", httpStatus: 200, redirectCount: 0, https: true, responseMs: 343, contentType: "text/html; charset=UTF-8", pageTitle: "Live Oak Bank | Business Loans &amp; Checking, High-Yield Savings", testedAt: "2026-06-14T14:57:40.236Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-035", canonicalResourceId: "vendor:the-hartford", providerName: "The Hartford", resourceType: "Provider - relationship unverified", originalUrl: "https://www.thehartford.com/business-insurance", finalUrl: "https://www.thehartford.com/business-insurance", normalizedDomain: "thehartford.com", finalDomain: "thehartford.com", httpStatus: 403, redirectCount: 0, https: true, responseMs: 160, contentType: "text/html", pageTitle: null, testedAt: "2026-06-14T14:57:40.186Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-036", canonicalResourceId: null, providerName: "Travelers", resourceType: "Provider - relationship unverified", originalUrl: "https://www.travelers.com/business-insurance", finalUrl: "https://www.travelers.com/business-insurance", normalizedDomain: "travelers.com", finalDomain: "travelers.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 637, contentType: "text/html; charset=utf-8", pageTitle: "Business and Commercial Insurance Policy Quotes | Travelers Insurance", testedAt: "2026-06-14T14:57:40.921Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-037", canonicalResourceId: null, providerName: "Liberty Mutual Business Insurance", resourceType: "Provider - relationship unverified", originalUrl: "https://business.libertymutual.com/", finalUrl: "https://business.libertymutual.com/", normalizedDomain: "business.libertymutual.com", finalDomain: "business.libertymutual.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 753, contentType: "text/html; charset=UTF-8", pageTitle: "Liberty Mutual Insurance - Liberty Mutual Business Insurance", testedAt: "2026-06-14T14:57:40.893Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-038", canonicalResourceId: null, providerName: "Nationwide Business Insurance", resourceType: "Provider - relationship unverified", originalUrl: "https://www.nationwide.com/business/insurance/", finalUrl: "https://www.nationwide.com/business/insurance/", normalizedDomain: "nationwide.com", finalDomain: "nationwide.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 1364, contentType: "text/html;charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:43.488Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-039", canonicalResourceId: null, providerName: "Progressive Commercial", resourceType: "Provider - relationship unverified", originalUrl: "https://www.progressivecommercial.com/", finalUrl: "https://www.progressivecommercial.com/", normalizedDomain: "progressivecommercial.com", finalDomain: "progressivecommercial.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 314, contentType: "text/html; charset=utf-8", pageTitle: "Commercial Insurance Quotes | Progressive Commercial", testedAt: "2026-06-14T14:57:40.817Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-040", canonicalResourceId: null, providerName: "State Farm Small Business Insurance", resourceType: "Provider - relationship unverified", originalUrl: "https://www.statefarm.com/small-business-solutions/insurance", finalUrl: "https://www.statefarm.com/insurance/small-business", normalizedDomain: "statefarm.com", finalDomain: "statefarm.com", httpStatus: 200, redirectCount: 1, https: true, responseMs: 323, contentType: "text/html; charset=utf-8", pageTitle: "Small Business Insurance - State Farm®", testedAt: "2026-06-14T14:57:41.528Z", classification: "healthy_with_redirect", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-041", canonicalResourceId: null, providerName: "Chubb Small Business", resourceType: "Provider - relationship unverified", originalUrl: "https://www.chubb.com/us-en/business-insurance/small-business.html", finalUrl: "https://www.chubb.com/us-en/business-insurance/small-business.html", normalizedDomain: "chubb.com", finalDomain: "chubb.com", httpStatus: 404, redirectCount: 0, https: true, responseMs: 309, contentType: "text/html;charset=utf-8", pageTitle: null, testedAt: "2026-06-14T14:57:41.126Z", classification: "permanent_failure", failureReason: "http_404", manualReviewRequired: false },
  { workbookResourceId: "VER-042", canonicalResourceId: null, providerName: "CNA", resourceType: "Provider - relationship unverified", originalUrl: "https://www.cna.com/web/guest/cna/home", finalUrl: "https://www.cna.com/", normalizedDomain: "cna.com", finalDomain: "cna.com", httpStatus: 200, redirectCount: 3, https: true, responseMs: 149, contentType: "text/html; charset=UTF-8", pageTitle: "Customized Business Insurance | CNA Insurance", testedAt: "2026-06-14T14:57:42.164Z", classification: "healthy_with_redirect", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-043", canonicalResourceId: null, providerName: "Zurich North America", resourceType: "Provider - relationship unverified", originalUrl: "https://www.zurichna.com/", finalUrl: "https://www.zurichna.com/", normalizedDomain: "zurichna.com", finalDomain: "zurichna.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 395, contentType: "text/html; charset=utf-8", pageTitle: null, testedAt: "2026-06-14T14:57:41.402Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-044", canonicalResourceId: "vendor:next-insurance", providerName: "ERGO NEXT", resourceType: "Public affiliate/embedded paths reported; terms must be verified", originalUrl: "https://www.nextinsurance.com/", finalUrl: "https://www.nextinsurance.com/", normalizedDomain: "nextinsurance.com", finalDomain: "nextinsurance.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 871, contentType: "text/html; charset=utf-8", pageTitle: "ERGO NEXT Insurance: Small Business Insurance Quotes Online", testedAt: "2026-06-14T14:57:42.431Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-045", canonicalResourceId: "vendor:simply-business", providerName: "Simply Business", resourceType: "Strategic partnership path reported; terms must be verified", originalUrl: "https://www.simplybusiness.com/", finalUrl: "https://www.simplybusiness.com/", normalizedDomain: "simplybusiness.com", finalDomain: "simplybusiness.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 164, contentType: "text/html; charset=UTF-8", pageTitle: "Small Business Insurance | Simply Business", testedAt: "2026-06-14T14:57:41.657Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-046", canonicalResourceId: null, providerName: "Thimble", resourceType: "Public affiliate path reported; terms must be verified", originalUrl: "https://www.thimble.com/", finalUrl: "https://www.thimble.com/", normalizedDomain: "thimble.com", finalDomain: "thimble.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 373, contentType: "text/html; charset=UTF-8", pageTitle: "Thimble Insurance: Online Insurance for Businesses", testedAt: "2026-06-14T14:57:42.065Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-047", canonicalResourceId: null, providerName: "Pie Insurance", resourceType: "Provider - relationship unverified", originalUrl: "https://pieinsurance.com/", finalUrl: "https://www.pieinsurance.com/", normalizedDomain: "pieinsurance.com", finalDomain: "pieinsurance.com", httpStatus: 200, redirectCount: 1, https: true, responseMs: 470, contentType: "text/html; charset=utf-8", pageTitle: "Pie Insurance | Small Business Insurance", testedAt: "2026-06-14T14:57:42.811Z", classification: "healthy_with_redirect", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-048", canonicalResourceId: "vendor:hiscox", providerName: "Hiscox", resourceType: "Provider - relationship unverified", originalUrl: "https://www.hiscox.com/small-business-insurance", finalUrl: "https://www.hiscox.com/small-business-insurance", normalizedDomain: "hiscox.com", finalDomain: "hiscox.com", httpStatus: 403, redirectCount: 0, https: true, responseMs: 89, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:42.059Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-049", canonicalResourceId: "vendor:biberk", providerName: "biBerk", resourceType: "Provider - relationship unverified", originalUrl: "https://www.biberk.com/", finalUrl: "https://www.biberk.com/", normalizedDomain: "biberk.com", finalDomain: "biberk.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 210, contentType: "text/html; charset=utf-8", pageTitle: "Small Business Insurance From biBerk | Get A Quote Online", testedAt: "2026-06-14T14:57:42.471Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-050", canonicalResourceId: null, providerName: "Insureon", resourceType: "Provider - relationship unverified", originalUrl: "https://www.insureon.com/", finalUrl: "https://www.insureon.com/", normalizedDomain: "insureon.com", finalDomain: "insureon.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 490, contentType: "text/html; charset=utf-8", pageTitle: "Buy Business Insurance: Instant Online Quotes | Insureon", testedAt: "2026-06-14T14:57:42.877Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-051", canonicalResourceId: null, providerName: "SuretyBonds.com", resourceType: "Provider - relationship unverified", originalUrl: "https://www.suretybonds.com/", finalUrl: "https://www.suretybonds.com/", normalizedDomain: "suretybonds.com", finalDomain: "suretybonds.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 388, contentType: "text/html; charset=utf-8", pageTitle: "Surety Bonds | Find Your Bond Online | SuretyBonds.com", testedAt: "2026-06-14T14:57:42.820Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-052", canonicalResourceId: "vendor:servicetitan", providerName: "ServiceTitan", resourceType: "Direct partnership path; terms unverified", originalUrl: "https://www.servicetitan.com/", finalUrl: "https://www.servicetitan.com/", normalizedDomain: "servicetitan.com", finalDomain: "servicetitan.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 258, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:42.911Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-053", canonicalResourceId: "vendor:housecall-pro", providerName: "Housecall Pro", resourceType: "Public affiliate/referral paths reported; terms must be verified", originalUrl: "https://www.housecallpro.com/", finalUrl: "https://www.housecallpro.com/", normalizedDomain: "housecallpro.com", finalDomain: "housecallpro.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 191, contentType: "text/html; charset=UTF-8", pageTitle: "Home Services Business Management Software - Housecall Pro", testedAt: "2026-06-14T14:57:42.721Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-054", canonicalResourceId: "vendor:jobber", providerName: "Jobber", resourceType: "Provider - partnership status unverified", originalUrl: "https://www.getjobber.com/", finalUrl: "https://www.getjobber.com/", normalizedDomain: "getjobber.com", finalDomain: "getjobber.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 327, contentType: "text/html; charset=utf-8", pageTitle: null, testedAt: "2026-06-14T14:57:43.338Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-055", canonicalResourceId: "vendor:fieldedge", providerName: "FieldEdge", resourceType: "Provider - relationship unverified", originalUrl: "https://fieldedge.com/", finalUrl: "https://fieldedge.com/", normalizedDomain: "fieldedge.com", finalDomain: "fieldedge.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 178, contentType: "text/html; charset=UTF-8", pageTitle: "Field Services Management Software &amp; Field Service App - FieldEdge", testedAt: "2026-06-14T14:57:43.133Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-056", canonicalResourceId: "vendor:workiz", providerName: "Workiz", resourceType: "Provider - relationship unverified", originalUrl: "https://www.workiz.com/", finalUrl: "https://www.workiz.com/", normalizedDomain: "workiz.com", finalDomain: "workiz.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 549, contentType: "text/html; charset=UTF-8", pageTitle: "Field Service Management (FSM) Software - Workiz", testedAt: "2026-06-14T14:57:44.651Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-057", canonicalResourceId: "vendor:service-fusion", providerName: "Service Fusion", resourceType: "Provider - relationship unverified", originalUrl: "https://www.servicefusion.com/", finalUrl: "https://www.servicefusion.com/", normalizedDomain: "servicefusion.com", finalDomain: "servicefusion.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 249, contentType: "text/html; charset=UTF-8", pageTitle: "Field Service Management Made Easy | Service Fusion", testedAt: "2026-06-14T14:57:43.283Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-058", canonicalResourceId: "vendor:fieldpulse", providerName: "FieldPulse", resourceType: "Provider - relationship unverified", originalUrl: "https://www.fieldpulse.com/", finalUrl: "https://www.fieldpulse.com/", normalizedDomain: "fieldpulse.com", finalDomain: "fieldpulse.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 301, contentType: "text/html", pageTitle: "FieldPulse | #1 Field Service Management Software", testedAt: "2026-06-14T14:57:43.385Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-059", canonicalResourceId: "vendor:buildops", providerName: "BuildOps", resourceType: "Provider - relationship unverified", originalUrl: "https://buildops.com/", finalUrl: "https://buildops.com/", normalizedDomain: "buildops.com", finalDomain: "buildops.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 249, contentType: "text/html; charset=utf-8", pageTitle: "BuildOps: Commercial Contractor Management Software", testedAt: "2026-06-14T14:57:43.512Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-060", canonicalResourceId: "vendor:simprogroup", providerName: "Simpro", resourceType: "Provider - relationship unverified", originalUrl: "https://www.simprogroup.com/", finalUrl: "https://www.simprogroup.com/", normalizedDomain: "simprogroup.com", finalDomain: "simprogroup.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 464, contentType: "text/html;charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:44.185Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-061", canonicalResourceId: "vendor:profit-rhino", providerName: "Profit Rhino", resourceType: "Provider - relationship unverified", originalUrl: "https://profitrhino.com/", finalUrl: "https://profitrhino.com/", normalizedDomain: "profitrhino.com", finalDomain: "profitrhino.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 416, contentType: "text/html; charset=UTF-8", pageTitle: "Profit Rhino Powered by Callahan Roach: Flat Rate Pricing &amp; Sales Tool for Residential Trades", testedAt: "2026-06-14T14:57:43.954Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-062", canonicalResourceId: null, providerName: "The New Flat Rate", resourceType: "Provider - relationship unverified", originalUrl: "https://thenewflatrate.com/", finalUrl: "https://thenewflatrate.com/", normalizedDomain: "thenewflatrate.com", finalDomain: "thenewflatrate.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 228, contentType: "text/html; charset=UTF-8", pageTitle: "Home", testedAt: "2026-06-14T14:57:43.740Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-063", canonicalResourceId: null, providerName: "Coolfront", resourceType: "Provider - relationship unverified", originalUrl: "https://www.coolfront.com/", finalUrl: "https://fieldedge.com/coolfront/", normalizedDomain: "coolfront.com", finalDomain: "fieldedge.com", httpStatus: 200, redirectCount: 1, https: true, responseMs: 148, contentType: "text/html; charset=UTF-8", pageTitle: "Coolfront: Now FieldEdge Flat Rate - FieldEdge", testedAt: "2026-06-14T14:57:43.963Z", classification: "domain_mismatch", failureReason: null, manualReviewRequired: true },
  { workbookResourceId: "VER-064", canonicalResourceId: null, providerName: "STACK", resourceType: "Provider - relationship unverified", originalUrl: "https://www.stackct.com/", finalUrl: "https://www.stackct.com/", normalizedDomain: "stackct.com", finalDomain: "stackct.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 225, contentType: "text/html; charset=UTF-8", pageTitle: "STACK | Cloud-Based Construction Software Solutions", testedAt: "2026-06-14T14:57:43.907Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-065", canonicalResourceId: null, providerName: "Bluebeam", resourceType: "Provider - relationship unverified", originalUrl: "https://www.bluebeam.com/", finalUrl: "https://www.bluebeam.com/", normalizedDomain: "bluebeam.com", finalDomain: "bluebeam.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 218, contentType: "text/html; charset=UTF-8", pageTitle: "Construction Collaboration Software - Bluebeam", testedAt: "2026-06-14T14:57:44.151Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-066", canonicalResourceId: null, providerName: "RSMeans Data", resourceType: "Provider - relationship unverified", originalUrl: "https://www.rsmeans.com/", finalUrl: "https://www.rsmeans.com/", normalizedDomain: "rsmeans.com", finalDomain: "rsmeans.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 227, contentType: "text/html; charset=UTF-8", pageTitle: "RSMeans Data: Construction Cost Estimating Software", testedAt: "2026-06-14T14:57:44.220Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-067", canonicalResourceId: null, providerName: "Johnstone Supply", resourceType: "Supplier - local account requirements", originalUrl: "https://www.johnstonesupply.com/", finalUrl: "https://www.johnstonesupply.com/", normalizedDomain: "johnstonesupply.com", finalDomain: "johnstonesupply.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 524, contentType: "text/html;charset=UTF-8", pageTitle: "Johnstone Supply | Wholesale Distributor to the HVAC, Refrigeration and Property Maintenance Industries", testedAt: "2026-06-14T14:57:44.847Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-068", canonicalResourceId: null, providerName: "R.E. Michel Company", resourceType: "Supplier - regional availability", originalUrl: "https://www.remichel.com/", finalUrl: "https://www.remichel.com/Webservices", normalizedDomain: "remichel.com", finalDomain: "remichel.com", httpStatus: 200, redirectCount: 1, https: true, responseMs: 161, contentType: "text/html; charset=utf-8", pageTitle: "R.E. Michel Company | Welcome!", testedAt: "2026-06-14T14:57:44.621Z", classification: "healthy_with_redirect", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-069", canonicalResourceId: null, providerName: "United Refrigeration", resourceType: "Supplier - branch availability", originalUrl: "https://www.uri.com/", finalUrl: "https://www.uri.com/", normalizedDomain: "uri.com", finalDomain: "uri.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 491, contentType: "text/html;charset=utf-8", pageTitle: "United Refrigeration Inc. | Refrigeration &amp; HVAC Replacement Parts and Equipment", testedAt: "2026-06-14T14:57:45.016Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-070", canonicalResourceId: null, providerName: "Ferguson", resourceType: "Supplier - trade account options", originalUrl: "https://www.ferguson.com/", finalUrl: "https://www.ferguson.com/", normalizedDomain: "ferguson.com", finalDomain: "ferguson.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 1415, contentType: "text/html;charset=UTF-8", pageTitle: "Plumbing Supplies, HVAC Parts, Pipe, Valves &amp; Fittings – Ferguson", testedAt: "2026-06-14T14:57:46.396Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-071", canonicalResourceId: null, providerName: "Winsupply", resourceType: "Supplier - local availability", originalUrl: "https://www.winsupplyinc.com/", finalUrl: "https://www.winsupplyinc.com/", normalizedDomain: "winsupplyinc.com", finalDomain: "winsupplyinc.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 417, contentType: "text/html", pageTitle: "Leading Supplier of Residential and Industrial Supplies", testedAt: "2026-06-14T14:57:44.809Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-072", canonicalResourceId: null, providerName: "Hajoca", resourceType: "Supplier - local brand availability", originalUrl: "https://www.hajoca.com/", finalUrl: "https://www.hajoca.com/", normalizedDomain: "hajoca.com", finalDomain: "hajoca.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 159, contentType: "text/html; charset=UTF-8", pageTitle: "Hajoca - Wholesale Plumbing, HVAC, Industrial, &amp; Pool Supplies", testedAt: "2026-06-14T14:57:44.890Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-073", canonicalResourceId: null, providerName: "Graybar", resourceType: "Supplier - account requirements", originalUrl: "https://www.graybar.com/", finalUrl: "https://www.graybar.com/", normalizedDomain: "graybar.com", finalDomain: "graybar.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 271, contentType: "text/html;charset=UTF-8", pageTitle: "Graybar | Electrical Supply, Datacom & Industrial Equipment Distributors", testedAt: "2026-06-14T14:57:45.128Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-074", canonicalResourceId: null, providerName: "Wesco", resourceType: "Supplier - account requirements", originalUrl: "https://www.wesco.com/", finalUrl: "https://www.wesco.com/", normalizedDomain: "wesco.com", finalDomain: "wesco.com", httpStatus: 403, redirectCount: 0, https: true, responseMs: 89, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:45.089Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-075", canonicalResourceId: null, providerName: "Sonepar USA", resourceType: "Supplier network - local brand availability", originalUrl: "https://www.soneparusa.com/", finalUrl: "https://www.soneparusa.com/", normalizedDomain: "soneparusa.com", finalDomain: "soneparusa.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 566, contentType: "text/html;charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:45.522Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-076", canonicalResourceId: null, providerName: "CED", resourceType: "Supplier - verify local operating company", originalUrl: "https://www.cedcareers.com/locations", finalUrl: "https://cedcareers.com/locations", normalizedDomain: "cedcareers.com", finalDomain: "cedcareers.com", httpStatus: 404, redirectCount: 1, https: true, responseMs: 510, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:45.762Z", classification: "permanent_failure", failureReason: "http_404", manualReviewRequired: false },
  { workbookResourceId: "VER-077", canonicalResourceId: null, providerName: "City Electric Supply", resourceType: "Supplier - branch availability", originalUrl: "https://www.cityelectricsupply.com/", finalUrl: "https://www.cityelectricsupply.com/", normalizedDomain: "cityelectricsupply.com", finalDomain: "cityelectricsupply.com", httpStatus: 403, redirectCount: 0, https: true, responseMs: 86, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:45.329Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-078", canonicalResourceId: null, providerName: "ABC Supply", resourceType: "Supplier - trade account requirements", originalUrl: "https://www.abcsupply.com/", finalUrl: "https://www.abcsupply.com/", normalizedDomain: "abcsupply.com", finalDomain: "abcsupply.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 167, contentType: "text/html; charset=UTF-8", pageTitle: "Home - ABC Supply", testedAt: "2026-06-14T14:57:45.351Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-079", canonicalResourceId: null, providerName: "SRS Distribution", resourceType: "Supplier - local brand availability", originalUrl: "https://www.srsdistribution.com/", finalUrl: "https://www.srsdistribution.com/", normalizedDomain: "srsdistribution.com", finalDomain: "srsdistribution.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 369, contentType: "text/html; charset=utf-8", pageTitle: "Roofing Materials &amp; Building Supplies | SRS Distribution", testedAt: "2026-06-14T14:57:45.697Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-080", canonicalResourceId: null, providerName: "Builders FirstSource", resourceType: "Supplier - regional product availability", originalUrl: "https://www.bldr.com/", finalUrl: "https://www.bldr.com/", normalizedDomain: "bldr.com", finalDomain: "bldr.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 235, contentType: "text/html;charset=UTF-8", pageTitle: "Builders FirstSource | Building Supplies &amp; Materials", testedAt: "2026-06-14T14:57:45.739Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-081", canonicalResourceId: null, providerName: "White Cap", resourceType: "Supplier - branch availability", originalUrl: "https://www.whitecap.com/", finalUrl: "https://www.whitecap.com/en-us", normalizedDomain: "whitecap.com", finalDomain: "whitecap.com", httpStatus: 403, redirectCount: 1, https: true, responseMs: 90, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:46.075Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-082", canonicalResourceId: null, providerName: "Grainger", resourceType: "Supplier - business account options", originalUrl: "https://www.grainger.com/", finalUrl: "https://www.grainger.com/", normalizedDomain: "grainger.com", finalDomain: "grainger.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 293, contentType: "text/html", pageTitle: "Whoops, we couldn't find that.", testedAt: "2026-06-14T14:57:46.085Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-083", canonicalResourceId: null, providerName: "Fastenal", resourceType: "Supplier - branch availability", originalUrl: "https://www.fastenal.com/", finalUrl: "https://www.fastenal.com/", normalizedDomain: "fastenal.com", finalDomain: "fastenal.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 281, contentType: "text/html;charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:46.249Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-084", canonicalResourceId: null, providerName: "SupplyHouse", resourceType: "Supplier - online availability", originalUrl: "https://www.supplyhouse.com/", finalUrl: "https://www.supplyhouse.com/", normalizedDomain: "supplyhouse.com", finalDomain: "supplyhouse.com", httpStatus: 403, redirectCount: 0, https: true, responseMs: 74, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:46.096Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-085", canonicalResourceId: "vendor:quickbooks", providerName: "QuickBooks Online", resourceType: "Provider - relationship unverified", originalUrl: "https://quickbooks.intuit.com/", finalUrl: "https://quickbooks.intuit.com/", normalizedDomain: "quickbooks.intuit.com", finalDomain: "quickbooks.intuit.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 300, contentType: "text/html", pageTitle: "QuickBooks®: Official Site | Smart Tools. Better Business.", testedAt: "2026-06-14T14:57:46.285Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-086", canonicalResourceId: "vendor:xero", providerName: "Xero", resourceType: "Provider - relationship unverified", originalUrl: "https://www.xero.com/us/", finalUrl: "https://www.xero.com/us/", normalizedDomain: "xero.com", finalDomain: "xero.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 290, contentType: "text/html", pageTitle: "Accounting Software for Small Businesses | Xero US", testedAt: "2026-06-14T14:57:46.527Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-087", canonicalResourceId: "vendor:gusto", providerName: "Gusto", resourceType: "Provider - relationship unverified", originalUrl: "https://gusto.com/", finalUrl: "https://gusto.com/", normalizedDomain: "gusto.com", finalDomain: "gusto.com", httpStatus: 403, redirectCount: 0, https: true, responseMs: 75, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:46.347Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-088", canonicalResourceId: "vendor:adp", providerName: "ADP", resourceType: "Provider - relationship unverified", originalUrl: "https://www.adp.com/", finalUrl: "https://www.adp.com/", normalizedDomain: "adp.com", finalDomain: "adp.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 555, contentType: "text/html; charset=utf-8", pageTitle: "Payroll, HR and Tax Services | ADP Official Site", testedAt: "2026-06-14T14:57:47.061Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-089", canonicalResourceId: "vendor:paychex", providerName: "Paychex", resourceType: "Provider - relationship unverified", originalUrl: "https://www.paychex.com/", finalUrl: "https://www.paychex.com/", normalizedDomain: "paychex.com", finalDomain: "paychex.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 178, contentType: "text/html; charset=UTF-8", pageTitle: "Paychex: Payroll &amp; HR Solutions", testedAt: "2026-06-14T14:57:46.536Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-090", canonicalResourceId: "vendor:clockshark", providerName: "ClockShark", resourceType: "Provider - relationship unverified", originalUrl: "https://www.clockshark.com/", finalUrl: "https://www.clockshark.com/", normalizedDomain: "clockshark.com", finalDomain: "clockshark.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 216, contentType: "text/html; charset=utf-8", pageTitle: "Field Service & Construction Time Tracking | ClockShark", testedAt: "2026-06-14T14:57:46.661Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-091", canonicalResourceId: null, providerName: "busybusy", resourceType: "Provider - relationship unverified", originalUrl: "https://busybusy.com/", finalUrl: "https://busybusy.com/", normalizedDomain: "busybusy.com", finalDomain: "busybusy.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 211, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:46.666Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-092", canonicalResourceId: null, providerName: "BILL", resourceType: "Provider - relationship unverified", originalUrl: "https://www.bill.com/", finalUrl: "https://www.bill.com/", normalizedDomain: "bill.com", finalDomain: "bill.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 205, contentType: "text/html; charset=utf-8", pageTitle: "BILL | Financial Operations Platform for Businesses &amp; Firms", testedAt: "2026-06-14T14:57:46.694Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-093", canonicalResourceId: null, providerName: "Google Business Profile", resourceType: "Official/free core product", originalUrl: "https://www.google.com/business/", finalUrl: "https://business.google.com/us/business-profile/", normalizedDomain: "google.com", finalDomain: "business.google.com", httpStatus: 200, redirectCount: 1, https: true, responseMs: 244, contentType: "text/html; charset=utf-8", pageTitle: "Get Listed on Google - Google Business Profile", testedAt: "2026-06-14T14:57:47.194Z", classification: "healthy_with_redirect", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-094", canonicalResourceId: "vendor:constant-contact", providerName: "Constant Contact", resourceType: "Public affiliate/partner paths reported; terms must be verified", originalUrl: "https://www.constantcontact.com/", finalUrl: "https://www.constantcontact.com/", normalizedDomain: "constantcontact.com", finalDomain: "constantcontact.com", httpStatus: 403, redirectCount: 0, https: true, responseMs: 92, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:46.773Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-095", canonicalResourceId: "vendor:mailchimp", providerName: "Mailchimp", resourceType: "Provider - relationship unverified", originalUrl: "https://mailchimp.com/", finalUrl: "https://mailchimp.com/", normalizedDomain: "mailchimp.com", finalDomain: "mailchimp.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 176, contentType: "text/html; charset=UTF-8", pageTitle: "Email &amp; SMS Marketing Platform | Mailchimp", testedAt: "2026-06-14T14:57:47.798Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-096", canonicalResourceId: "vendor:podium", providerName: "Podium", resourceType: "Referral/partner paths reported; terms must be verified", originalUrl: "https://www.podium.com/", finalUrl: "https://www.podium.com/", normalizedDomain: "podium.com", finalDomain: "podium.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 208, contentType: "text/html", pageTitle: "Podium: AI Lead Generation &amp; Lead Management Platform", testedAt: "2026-06-14T14:57:47.069Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-097", canonicalResourceId: "vendor:birdeye", providerName: "Birdeye", resourceType: "Provider - relationship unverified", originalUrl: "https://birdeye.com/", finalUrl: "https://birdeye.com/", normalizedDomain: "birdeye.com", finalDomain: "birdeye.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 352, contentType: null, pageTitle: "#1 Agentic Marketing Platform for Multi-location Brands | Birdeye", testedAt: "2026-06-14T14:57:47.360Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-098", canonicalResourceId: "vendor:nicejob", providerName: "NiceJob", resourceType: "Provider - relationship unverified", originalUrl: "https://nicejob.com/", finalUrl: "https://get.nicejob.com/", normalizedDomain: "nicejob.com", finalDomain: "get.nicejob.com", httpStatus: 200, redirectCount: 2, https: true, responseMs: 242, contentType: "text/html; charset=UTF-8", pageTitle: "Top-Rated Reputation Marketing Software for Local Businesses | NiceJob", testedAt: "2026-06-14T14:57:47.623Z", classification: "healthy_with_redirect", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-099", canonicalResourceId: "vendor:callrail", providerName: "CallRail", resourceType: "Provider - relationship unverified", originalUrl: "https://www.callrail.com/", finalUrl: "https://www.callrail.com/", normalizedDomain: "callrail.com", finalDomain: "callrail.com", httpStatus: 200, redirectCount: 0, https: true, responseMs: 257, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:47.546Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-100", canonicalResourceId: "vendor:openphone", providerName: "OpenPhone", resourceType: "Provider - relationship unverified", originalUrl: "https://www.openphone.com/", finalUrl: "https://www.quo.com/", normalizedDomain: "openphone.com", finalDomain: "quo.com", httpStatus: 200, redirectCount: 1, https: true, responseMs: 215, contentType: "text/html; charset=utf-8", pageTitle: "Quo (formerly OpenPhone) | Best Phone System for Startups &amp; Small Businesses", testedAt: "2026-06-14T14:57:47.614Z", classification: "domain_mismatch", failureReason: null, manualReviewRequired: true },
  { workbookResourceId: "VER-101", canonicalResourceId: null, providerName: "ACCA", resourceType: "Association/member resource", originalUrl: "https://www.acca.org/", finalUrl: "https://www.acca.org/home", normalizedDomain: "acca.org", finalDomain: "acca.org", httpStatus: 200, redirectCount: 1, https: true, responseMs: 255, contentType: "text/html; charset=utf-8", pageTitle: "Air Conditioning Contractors of America - ACCA", testedAt: "2026-06-14T14:57:48.135Z", classification: "healthy_with_redirect", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-102", canonicalResourceId: null, providerName: "NATE", resourceType: "Certification body", originalUrl: "https://www.natex.org/", finalUrl: "https://natex.org/", normalizedDomain: "natex.org", finalDomain: "natex.org", httpStatus: 200, redirectCount: 1, https: true, responseMs: 624, contentType: "text/html; charset=UTF-8", pageTitle: "Natex - NATE", testedAt: "2026-06-14T14:57:49.580Z", classification: "healthy_with_redirect", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-103", canonicalResourceId: null, providerName: "ESCO Institute", resourceType: "Certification/training provider", originalUrl: "https://www.escogroup.org/", finalUrl: "https://www.escogroup.org/", normalizedDomain: "escogroup.org", finalDomain: "escogroup.org", httpStatus: 403, redirectCount: 0, https: true, responseMs: 86, contentType: "text/html; charset=UTF-8", pageTitle: null, testedAt: "2026-06-14T14:57:47.854Z", classification: "blocked_or_rate_limited", failureReason: "http_403", manualReviewRequired: true },
  { workbookResourceId: "VER-104", canonicalResourceId: null, providerName: "NFPA", resourceType: "Nonprofit standards organization", originalUrl: "https://www.nfpa.org/", finalUrl: "https://www.nfpa.org/", normalizedDomain: "nfpa.org", finalDomain: "nfpa.org", httpStatus: 200, redirectCount: 0, https: true, responseMs: 265, contentType: "text/html; charset=utf-8", pageTitle: "NFPA | The National Fire Protection Association", testedAt: "2026-06-14T14:57:48.091Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-105", canonicalResourceId: null, providerName: "Independent Electrical Contractors", resourceType: "Association/member resource", originalUrl: "https://ieci.org/", finalUrl: "https://ieci.org/", normalizedDomain: "ieci.org", finalDomain: "ieci.org", httpStatus: 200, redirectCount: 0, https: true, responseMs: 448, contentType: "text/html; charset=UTF-8", pageTitle: "Electrical Trade Association | IECI", testedAt: "2026-06-14T14:57:48.300Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-106", canonicalResourceId: null, providerName: "PHCC", resourceType: "Association/member resource", originalUrl: "https://www.phccweb.org/", finalUrl: "https://www.phccweb.org/", normalizedDomain: "phccweb.org", finalDomain: "phccweb.org", httpStatus: 200, redirectCount: 0, https: true, responseMs: 440, contentType: "text/html; charset=UTF-8", pageTitle: "PHCC Home - PHCC", testedAt: "2026-06-14T14:57:48.519Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-107", canonicalResourceId: null, providerName: "IAPMO", resourceType: "Standards/certification organization", originalUrl: "https://www.iapmo.org/", finalUrl: "https://iapmo.org/", normalizedDomain: "iapmo.org", finalDomain: "iapmo.org", httpStatus: 200, redirectCount: 1, https: true, responseMs: 512, contentType: "text/html; charset=utf-8", pageTitle: "IAPMO Home | IAPMO", testedAt: "2026-06-14T14:57:49.056Z", classification: "healthy_with_redirect", failureReason: null, manualReviewRequired: false },
  { workbookResourceId: "VER-108", canonicalResourceId: null, providerName: "NCCER", resourceType: "Nonprofit education foundation", originalUrl: "https://www.nccer.org/", finalUrl: "https://www.nccer.org/", normalizedDomain: "nccer.org", finalDomain: "nccer.org", httpStatus: 200, redirectCount: 0, https: true, responseMs: 280, contentType: "text/html; charset=UTF-8", pageTitle: "National Center for Construction Education &amp; Research - NCCER", testedAt: "2026-06-14T14:57:48.497Z", classification: "healthy", failureReason: null, manualReviewRequired: false },
]

const FREE_EDUCATIONAL = /official\/free|government|nonprofit|association|standards|certification/i

/** Deterministic summary used by the audit doc + tests. */
export function summarizeLinkAudit(rows: ResourceLinkResult[] = RESOURCE_LINK_AUDIT) {
  const by = (k: (r: ResourceLinkResult) => string) =>
    rows.reduce<Record<string, number>>((a, r) => { const v = k(r); a[v] = (a[v] ?? 0) + 1; return a }, {})
  const healthy = rows.filter(r => r.classification === 'healthy' || r.classification === 'healthy_with_redirect')
  return {
    total: rows.length,
    classifications: by(r => r.classification),
    healthy: healthy.length,
    healthyHttps: healthy.filter(r => r.https).length,
    freeEducationalCandidates: healthy.filter(r => FREE_EDUCATIONAL.test(r.resourceType)).length,
    commercialHealthyHeld: healthy.filter(r => !FREE_EDUCATIONAL.test(r.resourceType)).length,
    manualReview: rows.filter(r => r.manualReviewRequired).length,
    activated: ACTIVATED_COUNT,
  }
}
