export interface SeedProduct {
  slug: string
  name: string
  description: string
  category: string
  website_url: string
  best_for: string
  poor_fit_for: string
  strengths: string[]
  limitations: string[]
  pricing_note: string
  free_plan_or_trial: boolean
  setup_complexity: 'easy' | 'moderate' | 'advanced'
}

export const seedProducts: SeedProduct[] = [
  {
    slug: 'systeme-io',
    name: 'Systeme.io',
    description: 'All-in-one platform for online business: funnels, email, courses, memberships, and affiliate management.',
    category: 'all-in-one',
    website_url: 'https://systeme.io',
    best_for: 'Solo entrepreneurs who want one platform for funnels, email, courses, and selling digital products without juggling multiple tools.',
    poor_fit_for: 'Teams needing advanced CRM, deep e-commerce inventory, or enterprise integrations.',
    strengths: ['Generous free plan', 'Built-in funnel builder', 'Email marketing included', 'Course and membership hosting', 'Affiliate program management'],
    limitations: ['Limited design customization', 'Fewer third-party integrations', 'Basic analytics compared to specialists'],
    pricing_note: 'Free plan available. Paid plans start at $27/month.',
    free_plan_or_trial: true,
    setup_complexity: 'easy',
  },
  {
    slug: 'mailerlite',
    name: 'MailerLite',
    description: 'Email marketing platform with automation, landing pages, and a website builder for growing audiences.',
    category: 'email-marketing',
    website_url: 'https://mailerlite.com',
    best_for: 'Creators and small businesses starting email marketing who want clean design, easy automation, and a generous free tier.',
    poor_fit_for: 'Businesses needing advanced CRM, complex multi-channel automation, or enterprise deliverability controls.',
    strengths: ['Clean intuitive interface', 'Generous free plan up to 1,000 subscribers', 'Built-in website and landing page builder', 'Solid automation workflows', 'Good deliverability reputation'],
    limitations: ['Limited advanced segmentation', 'No built-in CRM', 'Template variety is moderate'],
    pricing_note: 'Free up to 1,000 subscribers. Paid plans start at $10/month.',
    free_plan_or_trial: true,
    setup_complexity: 'easy',
  },
  {
    slug: 'kinsta',
    name: 'Kinsta',
    description: 'Premium managed WordPress hosting powered by Google Cloud with high performance and expert support.',
    category: 'hosting',
    website_url: 'https://kinsta.com',
    best_for: 'WordPress site owners who want fast, reliable managed hosting with expert support and automated backups.',
    poor_fit_for: 'Budget-conscious beginners or those not using WordPress.',
    strengths: ['Google Cloud infrastructure', 'Automatic daily backups', 'Free SSL and CDN', 'Expert WordPress support', 'Staging environments'],
    limitations: ['Higher price point than shared hosting', 'WordPress only', 'No email hosting included'],
    pricing_note: 'Plans start at $35/month for managed WordPress hosting.',
    free_plan_or_trial: false,
    setup_complexity: 'moderate',
  },
  {
    slug: 'getresponse',
    name: 'GetResponse',
    description: 'Email marketing and automation platform with conversion funnels, webinars, and landing pages.',
    category: 'email-marketing',
    website_url: 'https://getresponse.com',
    best_for: 'Marketers who need email automation combined with webinars, funnels, and landing pages in one platform.',
    poor_fit_for: 'Users who only need simple newsletters without marketing automation features.',
    strengths: ['Email and marketing automation', 'Built-in webinar hosting', 'Conversion funnel builder', 'Landing page creator', 'Good list segmentation'],
    limitations: ['Interface can feel complex for beginners', 'Webinar feature limited on lower tiers', 'Template editor could be more flexible'],
    pricing_note: 'Free plan available for up to 500 contacts. Paid plans start at $19/month.',
    free_plan_or_trial: true,
    setup_complexity: 'moderate',
  },
  {
    slug: 'kit',
    name: 'Kit (formerly ConvertKit)',
    description: 'Email marketing platform built for creators with visual automations, landing pages, and paid subscriptions.',
    category: 'email-marketing',
    website_url: 'https://kit.com',
    best_for: 'Content creators, writers, and course sellers who want subscriber-first email marketing with paid newsletter support.',
    poor_fit_for: 'E-commerce businesses needing product catalog integration or teams wanting complex multi-channel campaigns.',
    strengths: ['Built for creators', 'Visual automation builder', 'Paid newsletter and tip jar features', 'Clean subscriber management', 'Good deliverability'],
    limitations: ['Limited email template design options', 'No built-in CRM', 'Fewer integrations than larger platforms'],
    pricing_note: 'Free plan for up to 10,000 subscribers (limited features). Paid plans start at $25/month.',
    free_plan_or_trial: true,
    setup_complexity: 'easy',
  },
  {
    slug: 'beehiiv',
    name: 'beehiiv',
    description: 'Newsletter platform with built-in growth tools, monetization, and analytics designed for newsletter operators.',
    category: 'newsletter',
    website_url: 'https://beehiiv.com',
    best_for: 'Newsletter creators who want growth tools, ad monetization, referral programs, and audience analytics built in.',
    poor_fit_for: 'Businesses needing full marketing automation, CRM, or e-commerce beyond newsletters.',
    strengths: ['Newsletter-specific growth tools', 'Built-in ad network monetization', 'Referral program system', 'Clean writing experience', 'Custom website with SEO support'],
    limitations: ['Focused on newsletters only', 'Limited marketing automation', 'Younger platform with evolving features'],
    pricing_note: 'Free plan available. Paid plans start at $49/month.',
    free_plan_or_trial: true,
    setup_complexity: 'easy',
  },
  {
    slug: 'activecampaign',
    name: 'ActiveCampaign',
    description: 'Email marketing, automation, and CRM platform for businesses that need advanced multi-channel customer journeys.',
    category: 'email-marketing',
    website_url: 'https://activecampaign.com',
    best_for: 'Growing businesses that need deep automation, CRM integration, and multi-channel marketing in a single platform.',
    poor_fit_for: 'Beginners looking for a simple email newsletter tool or very small lists.',
    strengths: ['Powerful automation builder', 'Built-in CRM', 'Advanced segmentation and personalization', 'Multi-channel marketing', 'Extensive integrations'],
    limitations: ['Steeper learning curve', 'More expensive than simpler alternatives', 'CRM is mid-tier compared to dedicated CRM tools'],
    pricing_note: 'Plans start at $29/month. No free plan; 14-day free trial available.',
    free_plan_or_trial: false,
    setup_complexity: 'advanced',
  },
  {
    slug: 'shopify',
    name: 'Shopify',
    description: 'E-commerce platform for building online stores with payments, inventory, shipping, and multichannel selling.',
    category: 'ecommerce',
    website_url: 'https://shopify.com',
    best_for: 'Anyone selling physical or digital products who wants a complete, reliable e-commerce platform with payment processing.',
    poor_fit_for: 'Content-only sites, blogs, or businesses that do not sell products directly.',
    strengths: ['Complete e-commerce solution', 'Built-in payment processing', 'Huge app ecosystem', 'Multichannel selling', 'Reliable and scalable'],
    limitations: ['Transaction fees on third-party gateways', 'Template customization has limits without coding', 'Monthly costs add up with apps'],
    pricing_note: 'Plans start at $39/month. 3-day free trial available.',
    free_plan_or_trial: false,
    setup_complexity: 'moderate',
  },
  {
    slug: 'semrush',
    name: 'Semrush',
    description: 'All-in-one SEO and digital marketing toolkit for keyword research, site audits, competitor analysis, and content planning.',
    category: 'seo',
    website_url: 'https://semrush.com',
    best_for: 'Marketers and business owners serious about SEO who need keyword research, competitor analysis, and site auditing tools.',
    poor_fit_for: 'Beginners on a tight budget or businesses not yet focused on organic search growth.',
    strengths: ['Comprehensive keyword research', 'Competitor analysis', 'Site audit tools', 'Content marketing toolkit', 'Backlink analysis'],
    limitations: ['Premium pricing', 'Can be overwhelming for beginners', 'Some features require higher-tier plans'],
    pricing_note: 'Plans start at $139.95/month. 7-day free trial available.',
    free_plan_or_trial: false,
    setup_complexity: 'advanced',
  },
  {
    slug: 'instantly',
    name: 'Instantly',
    description: 'Cold email outreach and lead generation platform for B2B sales teams with unlimited email accounts and warmup.',
    category: 'outreach',
    website_url: 'https://instantly.ai',
    best_for: 'B2B sales teams and agencies running cold email campaigns who need unlimited email accounts and deliverability tools.',
    poor_fit_for: 'Newsletter senders, e-commerce businesses, or anyone not doing outbound B2B prospecting.',
    strengths: ['Unlimited email accounts', 'Built-in email warmup', 'Campaign analytics', 'Lead database access', 'Simple campaign builder'],
    limitations: ['Focused only on cold outreach', 'No marketing automation', 'Deliverability depends on domain reputation management'],
    pricing_note: 'Plans start at $37/month for outreach features.',
    free_plan_or_trial: false,
    setup_complexity: 'moderate',
  },
]

export const categories = [
  { slug: 'all-in-one', name: 'All-in-One Platforms', description: 'Complete business platforms combining multiple tools.' },
  { slug: 'email-marketing', name: 'Email Marketing', description: 'Platforms for email campaigns, automation, and list management.' },
  { slug: 'hosting', name: 'Web Hosting', description: 'Website hosting solutions for performance and reliability.' },
  { slug: 'newsletter', name: 'Newsletter Platforms', description: 'Tools for publishing and monetizing email newsletters.' },
  { slug: 'ecommerce', name: 'E-Commerce', description: 'Online store builders and e-commerce platforms.' },
  { slug: 'seo', name: 'SEO Tools', description: 'Search engine optimization research and auditing tools.' },
  { slug: 'outreach', name: 'Outreach & Sales', description: 'Cold outreach and B2B lead generation tools.' },
]

export const useCases = [
  { slug: 'start-online-business', name: 'Start an Online Business', icon: '🚀' },
  { slug: 'build-website', name: 'Build a Website', icon: '🌐' },
  { slug: 'grow-email-list', name: 'Grow an Email List', icon: '📧' },
  { slug: 'launch-newsletter', name: 'Launch a Newsletter', icon: '📰' },
  { slug: 'sell-online', name: 'Sell Online', icon: '🛒' },
  { slug: 'automate-marketing', name: 'Automate Marketing', icon: '⚡' },
  { slug: 'improve-seo', name: 'Improve SEO', icon: '📈' },
  { slug: 'run-b2b-outreach', name: 'Run B2B Outreach', icon: '🎯' },
]

export const comparisons = [
  { slug: 'systeme-io-vs-mailerlite', title: 'Systeme.io vs MailerLite', productA: 'systeme-io', productB: 'mailerlite', bestForA: 'All-in-one business building', bestForB: 'Focused email marketing' },
  { slug: 'mailerlite-vs-kit', title: 'MailerLite vs Kit', productA: 'mailerlite', productB: 'kit', bestForA: 'Cost-effective email marketing', bestForB: 'Creator-focused email and monetization' },
  { slug: 'mailerlite-vs-getresponse', title: 'MailerLite vs GetResponse', productA: 'mailerlite', productB: 'getresponse', bestForA: 'Simple, clean email marketing', bestForB: 'Email marketing with webinars and funnels' },
  { slug: 'kit-vs-beehiiv', title: 'Kit vs beehiiv', productA: 'kit', productB: 'beehiiv', bestForA: 'Creator email with paid subscriptions', bestForB: 'Newsletter growth and ad monetization' },
  { slug: 'kinsta-vs-budget-hosting', title: 'Kinsta vs Budget Hosting', productA: 'kinsta', productB: 'kinsta', bestForA: 'Premium managed WordPress performance', bestForB: 'Lower cost for simpler sites' },
  { slug: 'shopify-vs-website-builders', title: 'Shopify vs Website Builders', productA: 'shopify', productB: 'systeme-io', bestForA: 'Dedicated e-commerce with inventory', bestForB: 'All-in-one with simpler selling' },
  { slug: 'activecampaign-vs-getresponse', title: 'ActiveCampaign vs GetResponse', productA: 'activecampaign', productB: 'getresponse', bestForA: 'Advanced automation and CRM', bestForB: 'Marketing automation with webinars' },
  { slug: 'semrush-vs-beginner-seo', title: 'Semrush vs Beginner SEO Tools', productA: 'semrush', productB: 'semrush', bestForA: 'Comprehensive SEO for serious marketers', bestForB: 'Simpler SEO for beginners' },
]
